const questions = {
  c1s1: [
    { pl: "dane osobowe", en: "personal data" },
    { pl: "adres", en: "address" },
    { pl: "wiek", en: "age" },
    { pl: "data urodzenia", en: "date of birth" },
    { pl: "rozwiedziony", en: "divorced" },
    { pl: "kobieta", en: "female" },
    { pl: "imię", en: "first name" },
    { pl: "płeć", en: "gender" },
    { pl: "mężczyzna", en: "male" },
    { pl: "stan cywilny", en: "marital status" },
    { pl: "żonaty/zamężna", en: "married" },
    { pl: "narodowość", en: "nationality" },
    { pl: "zawód", en: "occupation" },
    { pl: "stanu wolnego", en: "single" },
    { pl: "nazwisko", en: "surname" },
    { pl: "owdowiały", en: "widowed" },
    { pl: "kraj zamieszkania", en: "country of residence" },
    { pl: "znaki szczególne", en: "distinguishing features" },
    { pl: "pochodzenie etniczne", en: "ethnic origin" },
    { pl: "najbliższy krewny", en: "next of kin" }
  ],
  c1s2: [
    { pl: "wygląd zewętrzny", en: "appearance" },
    { pl: "atrakcyjny/nieatrakcyjny", en: "attractive/unattractive" },
    { pl: "piękny", en: "beautiful" },
    { pl: "sprawny", en: "fit" },
    { pl: "przystojny, ładny", en: "good-looking" },
    { pl: "przystojny", en: "handsome" },
    { pl: "pospolity, nieatrakcyjny", en: "plain" },
    { pl: "ładny", en: "pretty" },
    { pl: "brzydki", en: "ugly" },
    { pl: "ograniczać", en: "cut down on", tip: "ilość czegoś" },
    { pl: "wybierać, sięgać po", en: "go for", tip: "ciemniejsze kolory" },
    { pl: "malować paznokcie", en: "paint nails" },
    { pl: "przybierać/tracić", en: "put on/lose", tip: "na wadze" },
    { pl: "prostować", en: "straighten", tip: "włosy" },
    { pl: "zacząć", en: "take up", tip: "hobby, sport" },
    { pl: "gruby", en: "fat" },
    { pl: "umięśniony", en: "muscular" },
    { pl: "otyły", en: "obese" },
    { pl: "z nadwagą/z niedowagą", en: "overweight/underweight" },
    { pl: "puszysty/pulchny", en: "plump" },
    { pl: "chudy", en: "skinny" },
    { pl: "szczupły", en: "slim" },
    { pl: "dobrze zbudowany", en: "well-built" },
    { pl: "tyczkowaty, wysoki i chudy", en: "lanky" },
    { pl: "krępy", en: "stocky" },
    { pl: "łysy", en: "bald" },
    { pl: "blond", en: "blond" },
    { pl: "kręcone", en: "curly" },
    { pl: "ciemne", en: "dark" },
    { pl: "farbowane", en: "dyed" },
    { pl: "rude", en: "red" },
    { pl: "do ramion", en: "shoulder-length" },
    { pl: "proste", en: "straight" },
    { pl: "falujące", en: "wavy" },
    { pl: "kasztanowe", en: "auburn" },
    { pl: "cienkie, rzadkie/gęste", en: "fine/thick" },
    { pl: "grzywka", en: "fringe" },
    { pl: "mieć przedziałek na środku/z boku", en: "have a center/side parting" },
    { pl: "kita, koński, ogon", en: "ponytail" },
    { pl: "włosy rzednące na skroniach", en: "receding hairline" },
    { pl: "nosić włosy rozpuszczone/spięte", en: "wear your hair loose/up" },
    { pl: "broda", en: "beard" },
    { pl: "piegi", en: "freckles" },
    { pl: "wąsy", en: "moustache" },
    { pl: "blada/opalona/ciemna cera", en: "pale/tanned/dark complexion" },
    { pl: "przekłute uszy", en: "pierced ears" },
    { pl: "blizna", en: "scar" },
    { pl: "pryszczaty", en: "spotty" },
    { pl: "tatuaż", en: "tattoo" },
    { pl: "zmarszczki", en: "wrinkles" },
    { pl: "znamię", en: "birthmark" },
    { pl: "gładko ogolony", en: "clean-shaven" },
    { pl: "gładka skóra", en: "clear-skin" },
    { pl: "podwójny podbródek", en: "double chin" },
    { pl: "wystające kości policzkowe", en: "high cheekbones" },
    { pl: "wysokie czoło", en: "high forehead" },
    { pl: "przenikliwe niebieskie oczy", en: "piercing blue eyes" }
  ],
  c1s3: [
    { pl: "bluzka", en: "blouse" },
    { pl: "wysokie buty, kozaki", en: "boots" },
    { pl: "biustonosz", en: "bra" },
    { pl: "codzienny, swobodny", en: "casual" },
    { pl: "płaszcz", en: "coat" },
    { pl: "sukienka", en: "dress" },
    { pl: "modny", en: "fashionable/trendy" },
    { pl: "bluza polarowa", en: "fleece" },
    { pl: "rękawiczki", en: "gloves" },
    { pl: "kapelusz, czapka", en: "hat" },
    { pl: "kurtka, marynarka, żakiet", en: "jacket" },
    { pl: "dżinsy", en: "jeans" },
    { pl: "sweter", en: "jumper" },
    { pl: "staromodny, staroświecki", en: "old-fashioned" },
    { pl: "piżama", en: "pyjamas" },
    { pl: "sandały", en: "sandals" },
    { pl: "koszula", en: "shirt" },
    { pl: "buty", en: "shoes" },
    { pl: "szorty", en: "shorts" },
    { pl: "spódnica", en: "skirt" },
    { pl: "elegancki", en: "smart" },
    { pl: "skarpety", en: "socks" },
    { pl: "garnitur", en: "suit" },
    { pl: "bluza sportowa", en: "sweatshirt" },
    { pl: "krawat", en: "tie" },
    { pl: "dres", en: "tracksuit" },
    { pl: "obuwie sportowe", en: "trainers" },
    { pl: "spodnie", en: "trousers" },
    { pl: "bielizna", en: "underwear" },
    { pl: "kamizelka", en: "waistcoat" },
    { pl: "nosić, mieć na sobie", en: "wear" },
    { pl: "suknia balowa, strój balowy", en: "ballgown" },
    { pl: "z szerokim dekoltem", en: "boat-necked" },
    { pl: "rozpinany sweter", en: "cardigan" },
    { pl: "kołnierzyk", en: "collar" },
    { pl: "mankiety", en: "cuffs" },
    { pl: "szlafrok", en: "dressing gown" },
    { pl: "wysokie obcasy", en: "high heels" },
    { pl: "bluza z kapturem", en: "hoodie" },
    { pl: "z długim rękawem/z krótkim rękawem", en: "long-sleeved/short-sleeved" },
    { pl: "bluzka bez ramiączek", en: "strapless top" },
    { pl: "dekolt w szpic", en: "V-neck" },
    { pl: "dodatki", en: "accessories" },
    { pl: "pasek", en: "belt" },
    { pl: "guzik", en: "button" },
    { pl: "czapka z daszkiem", en: "cap" },
    { pl: "kolczyki", en: "earrings" },
    { pl: "okulary", en: "glasses" },
    { pl: "torebka", en: "handbag/bag" },
    { pl: "biżuteria", en: "jewellery" },
    { pl: "naszyjnik", en: "necklace" },
    { pl: "pierścionek", en: "ring" },
    { pl: "szalik", en: "scarf" },
    { pl: "krawat", en: "tie" },
    { pl: "bransoletka", en: "bracelet" },
    { pl: "broszka", en: "brooch" },
    { pl: "sznurówki", en: "shoe laces" },
    { pl: "kapcie", en: "slippers" },
    { pl: "na zamek", en: "zip-up" },
    { pl: "w kratę", en: "checked" },
    { pl: "bawełna", en: "cotton" },
    { pl: "złoto", en: "gold" },
    { pl: "skóra, skórzany", en: "leather" },
    { pl: "gładki", en: "plain" },
    { pl: "jedwab", en: "silk" },
    { pl: "srebro, srebrny", en: "silver" },
    { pl: "w kropki", en: "spotted" },
    { pl: "w paski", en: "stripped" },
    { pl: "w szkocką kratę", en: "tartan" },
    { pl: "wełna", en: "wool" },
    { pl: "elastyczny", en: "elastic" },
    { pl: "futro, futrzany", en: "fur" },
    { pl: "koronkowy", en: "lacy" },
    { pl: "na doszewce, ocieplany", en: "lined" }
  ],
  c1s4: [
    { pl: "agresywny", en: "aggressive" },
    { pl: "ambitny", en: "ambitious" },
    { pl: "wybuchowy", en: "bad-tempered" },
    { pl: "zarozumiały", en: "big-headed" },
    { pl: "odważny", en: "brave" },
    { pl: "ostrożny/nieostrożny", en: "careful/careless" },
    { pl: "troskliwy", en: "caring" },
    { pl: "radosny, pogodny", en: "cheerful" },
    { pl: "mądry", en: "clever" },
    { pl: "pewny siebie/zbyt pewny siebie", en: "confident/overconfident" },
    { pl: "panikarz, osoba nadmiernie dramatyzująca", en: "drama queen" },
    { pl: "wyluzowany, opanowany", en: "easygoing" },
    { pl: "energiczny", en: "energetic" },
    { pl: "ekstrawertyk", en: "extrovert" },
    { pl: "przyjacielski, miły", en: "friendly" },
    { pl: "lubiący dobrą zabawę", en: "fun-loving" },
    { pl: "szczodry, hojny", en: "generous" },
    { pl: "delikatny, łagodny", en: "gentle" },
    { pl: "pracowity", en: "hard-working" },
    { pl: "uczynny/nieskory do pomocy", en: "helpful/unhelpful" },
    { pl: "uczciwy/nieuczciwy", en: "honest/dishonest" },
    { pl: "pomysłowy, kreatywny/bez wyobraźni", en: "imaginative/unimaginative" },
    { pl: "niezależny", en: "independent" },
    { pl: "inteligentny", en: "intelligent" },
    { pl: "introwertyk", en: "introvert" },
    { pl: "leniwy", en: "lazy" },
    { pl: "skąpy, złośliwy", en: "mean" },
    { pl: "bałaganiarski", en: "messy" },
    { pl: "złośliwy, wstrętny", en: "nasty" },
    { pl: "miły", en: "nice" },
    { pl: "otwarty", en: "open" },
    { pl: "optymistyczny", en: "optimistic" },
    { pl: "pesymistyczny", en: "pessimistic" },
    { pl: "otwarty, towarzyski", en: "outgoing" },
    { pl: "cierpliwy", en: "patient" },
    { pl: "niecierpliwy", en: "impatient" },
    { pl: "uprzejmy", en: "polite" },
    { pl: "cichy", en: "quiet" },
    { pl: "solidny, niezawodny/niesolidny, zawodny", en: "reliable/unreliable" },
    { pl: "odpowiedzialny", en: "responsible" },
    { pl: "niegrzeczny", en: "rude" },
    { pl: "samolubny/bezinteresowny", en: "selfish/unselfish" },
    { pl: "poważny", en: "serious" },
    { pl: "nieśmiały", en: "shy" },
    { pl: "niemądry, głupkowaty", en: "silly" },
    { pl: "towarzyski/nietowarzyski", en: "sociable/unsociable" },
    { pl: "gadatliwy, rozmowny", en: "talkative" },
    { pl: "schludny, porządny/niechlujny", en: "tidy/untidy" },
    { pl: "apodyktyczny", en: "bossy" },
    { pl: "tchórzliwy", en: "cowardly" },
    { pl: "ekscentryczny", en: "eccentric" },
    { pl: "materialistyczny", en: "materialistic" },
    { pl: "skromny", en: "modest" },
    { pl: "kapryśny", en: "moody" },
    { pl: "dziwny", en: "odd" },
    { pl: "dziwak", en: "oddball" },
    { pl: "wrażliwy", en: "sensitive" },
    { pl: "szczery", en: "sincere" },
    { pl: "życzliwy, współczujący", en: "sympathetic" },
    { pl: "dziwny", en: "weird" },
    { pl: "dziwak/dziwaczka, dziwadło", en: "weirdo" },
    { pl: "cudowne dziecko", en: "whizzkid" },
    { pl: "zamknięty w sobie", en: "withdrawn" },
  ],
  c1s5: [
    { pl: "zły, rozgniewany", en: "angry" },
    { pl: "zirytowany, rozdrażniony", en: "annoyed" },
    { pl: "być w dobrym/złym humorze", en: "be in a good/bad mood" },
    { pl: "znudzony", en: "bored" },
    { pl: "zły, rozgniewany", en: "cross" },
    { pl: "załamany, przygnębiony", en: "depressed" },
    { pl: "rozczarowany,zawiedziony", en: "disappointed" },
    { pl: "zawstydzony", en: "embarrassed" },
    { pl: "podekscytowany", en: "excited" },
    { pl: "wyczerpany, zmęczony", en: "exhausted" },
    { pl: "przerażony", en: "frightened" },
    { pl: "zdenerwowany, spięty", en: "nervous" },
    { pl: "zadowolony", en: "pleased" },
    { pl: "zrelaksowany", en: "relaxed" },
    { pl: "wystraszony", en: "scared" },
    { pl: "zszokowany", en: "shocked" },
    { pl: "zestresowany", en: "stressed" },
    { pl: "zdziwiony, zaskoczony", en: "surprised" },
    { pl: "zmęczony", en: "tired" },
    { pl: "przygnębiony, zaniepokojony", en: "upset" },
    { pl: "zmartwiony", en: "worried" },
    { pl: "zdumiony, zdziwiony", en: "amazed" },
    { pl: "zachwycony", en: "delighted" },
    { pl: "dręczące uczucie", en: "nagging feeling" },
    { pl: "przerażony", en: "petrified" },
    { pl: "zdruzgotany, wykończony", en: "shattered" },
    { pl: "oniemiały, osłupiały", en: "stunned" },
    { pl: "wycieńczony, wyczerpany", en: "worn out" },
  ],
  c1s6: [
    { pl: "uwielbiać", en: "adore" },
    { pl: "być fanem kogoś/czegoś", en: "be a fan of sb/sth" },
    { pl: "być beznadziejnym w", en: "be hopeless at" },
    { pl: "interesować się czymś", en: "be interested in sth" },
    { pl: "zajmować się czymś, interesować", en: "be into sth" },
    { pl: "interesować się, lubić coś robić", en: "be keen on sth" },
    { pl: "szaleć za kimś/czymś", en: "be mad about sb/sth" },
    { pl: "nie znosić", en: "can't stand" },
    { pl: "grać w gry/gry planszowe", en: "play games/board games" },
    { pl: "ćwiczyć", en: "work out" },
  ],
  c1s7: [
    { pl: "aborcja", en: "abortion" },
    { pl: "dobroczynność, organizacja charytatywna", en: "charity" },
    { pl: "zażywanie narkotyk", en: "drug abuse" },
    { pl: "sprawiedliwy handel", en: "fair trade" },
    { pl: "bezdomność", en: "homelessness" },
    { pl: "bezrobocie", en: "unemployment" },
    { pl: "korupcja", en: "corruption" },
    { pl: "rasizm", en: "racism" },
    { pl: "kara śmierci", en: "death penalty" },
    { pl: "eutanazja", en: "euthanasia" },
    { pl: "wolność słowa", en: "freedom of speech" },
    { pl: "hazard", en: "gambling" },
    { pl: "inżynieria genetyczna", en: "genetic engineering" },
    { pl: "prywatność", en: "privacy" },
  ],
  c1s8: [
    { pl: "krótki, krótkotrwały", en: "brief" },
    { pl: "wpaść na, natknąć się na", en: "come across" },
    { pl: "całkowity, kompletny", en: "complete" },
    { pl: "rozwinąć się w, stawać się", en: "develop into", tip: "kimś" },
    { pl: "fanatyk/fanatyczka ekologii", en: "eco-freak" },
    { pl: "fanatyk/fanatyczka ćwiczeń fizycznych", en: "fitness maniac" },
    { pl: "skupiać się na", en: "focus on" },
    { pl: "rosnąć, dorastać", en: "grow up" },
    { pl: "mieć dużo/niewiele wspólnego", en: "have a lot/little in common" },
    { pl: "osoba mająca obsesję na punkcie zdrowia", en: "health nut" },
    { pl: "ogromny", en: "huge" },
    { pl: "zidentyfikować", en: "identify" },
    { pl: "podziwiać", en: "look up to" },
    { pl: "zdać sobie sprawę", en: "realise" },
    { pl: "rozpoznać", en: "recognise" },
    { pl: "pamiętać", en: "remember" },
    { pl: "przypomnieć komuś, by coś zrobił", en: "remind someone to do something" },
    { pl: "wydawać pieniądze na", en: "spend money on" },
    { pl: "dostrzec", en: "spot" },
    { pl: "całkowite przeciwieństwo", en: "the complete opposite" },
    { pl: "typowy dla", en: "typical of" },
    { pl: "leżeć w czyjejś naturze", en: "be part of someone's nature" },
    { pl: "zaprzyjaźnić się z", en: "befriend" },
    { pl: "dziwny", en: "bizarre" },
    { pl: "nie móc uwierzyć własnym uszom", en: "can't believe your ears" },
    { pl: "częste doznanie", en: "common experience" },
    { pl: "znaleźć wspólną płaszczyznę", en: "find common ground" },
    { pl: "doskonale się bawić", en: "have the time of your life" },
    { pl: "rozpoznać, zidentyfikować", en: "place" },
    { pl: "zdobyć się na odwagę", en: "pluck up the courage", tip: "aby coś zrobić" },
    { pl: "nasuwać pytania", en: "raise questions" },
    { pl: "przeskanować, przebiec wzrokiem", en: "scan", tip: "mózg, tekst" },
    { pl: "skomplikowany, zaawansowany", en: "sophisticated" },
    { pl: "nawiązać", en: "strike up", tip: "konwersację" }
  ],
  c2s1: [
    { pl: "x", en: "x" },
  ],
  c2s2: [
    { pl: "x", en: "x" },
  ],
  c2s3: [
    { pl: "x", en: "x" },
  ],
  c2s4: [
    { pl: "x", en: "x" },
  ],
  c2s5: [
    { pl: "x", en: "x" },
  ],
  c3s1: [
    { pl: "x", en: "x" },
  ],
  c3s2: [
    { pl: "x", en: "x" },
  ],
  c3s3: [
    { pl: "x", en: "x" },
  ],
  c3s4: [
    { pl: "x", en: "x" },
  ],
  c3s5: [
    { pl: "x", en: "x" },
  ],
  c3s6: [
    { pl: "x", en: "x" },
  ],
  c4s1: [
    { pl: "x", en: "x" },
  ],
  c4s2: [
    { pl: "x", en: "x" },
  ],
  c4s3: [
    { pl: "x", en: "x" },
  ],
  c4s4: [
    { pl: "x", en: "x" },
  ],
  c4s5: [
    { pl: "x", en: "x" },
  ],
  c5s1: [
    { pl: "x", en: "x" },
  ],
  c5s2: [
    { pl: "x", en: "x" },
  ],
  c5s3: [
    { pl: "x", en: "x" },
  ],
  c5s4: [
    { pl: "x", en: "x" },
  ],
  c5s5: [
    { pl: "x", en: "x" },
  ],
  c5s6: [
    { pl: "x", en: "x" },
  ],
  c5s7: [
    { pl: "x", en: "x" },
  ],

  // Add more questions as needed
};

// cxs1: [
//   { pl: "x", en: "x" },
// ],
// cxs2: [
//   { pl: "x", en: "x" },
// ],
// cxs3: [
//   { pl: "x", en: "x" },
// ],
// cxs4: [
//   { pl: "x", en: "x" },
// ],
// cxs5: [
//   { pl: "x", en: "x" },
// ],
// cxs6: [
//   { pl: "x", en: "x" },
// ],
// cxs7: [
//   { pl: "x", en: "x" },
// ],