const allQuestions = {
  c1s1: [
    { pl: "adres", en: "address", example: {en: "Provide your address.", pl: "Podaj swój adres."} },
    { pl: "wiek", en: "age", example: {en: "State your age.", pl: "Podaj swój wiek."} },
    { pl: "data urodzenia", en: "date of birth", example: {en: "Enter your date of birth.", pl: "Podaj swoją datę urodzenia."} },
    { pl: "rozwiedziony", en: "divorced", example: {en: "He is divorced.", pl: "On jest rozwiedziony."} },
    { pl: "kobieta", en: "female", example: {en: "She is female.", pl: "Ona jest kobietą."} },
    { pl: "imię", en: "first name", example: {en: "Provide your first name.", pl: "Podaj swoje imię."} },
    { pl: "płeć", en: "gender", example: {en: "Indicate your gender.", pl: "Określ swoją płeć."} },
    { pl: "mężczyzna", en: "male", example: {en: "He is male.", pl: "On jest mężczyzną."} },
    { pl: "stan cywilny", en: "marital status", example: {en: "Specify your marital status.", pl: "Określ swój stan cywilny."} },
    { pl: "żonaty/zamężna", en: "married", example: {en: "He/She is married.", pl: "On/Ona jest żonaty/zamżęna."} },
    { pl: "narodowość", en: "nationality", example: {en: "State your nationality.", pl: "Podaj swoją narodowość."} },
    { pl: "zawód", en: "occupation", example: {en: "State your occupation.", pl: "Podaj swoje zawód."} },
    { pl: "dane osobowe", en: "personal data", example: {en: "Provide your personal data.", pl: "Podaj swoje dane osobowe."} },
    { pl: "stanu wolnego", en: "single", example: {en: "He is single.", pl: "On jest stanu wolnego."} },
    { pl: "nazwisko", en: "surname", example: {en: "Provide your surname.", pl: "Podaj swoje nazwisko."} },
    { pl: "owdowiały", en: "widowed", example: {en: "She is widowed.", pl: "Ona jest owdowiała."} },
    { pl: "kraj zamieszkania", en: "country of residence", example: {en: "Specify your country of residence.", pl: "Podaj swój kraj zamieszkania."} },
    { pl: "znaki szczególne", en: "distinguishing features", example: {en: "Describe any distinguishing features.", pl: "Opisz wszelkie znaki szczególne."} },
    { pl: "pochodzenie etniczne", en: "ethnic origin", example: {en: "State your ethnic origin.", pl: "Podaj swoje pochodzenie etniczne."} },
    { pl: "najbliższy krewny", en: "next of kin", example: {en: "Provide details of your next of kin.", pl: "Podaj szczegóły swojego najbliższego krewnego."} },
  ],
  c1s2: [
    { pl: "wygląd zewętrzny", en: "appearance" },
    { pl: "atrakcyjny/nieatrakcyjny", en: "attractive/unattractive" },
    { pl: "piękny", en: "beautiful" },
    { pl: "sprawny", en: "fit" },
    { pl: "przystojny, ładny", en: "good-looking" },
    { pl: "przystojny", en: "handsome" },
    { pl: "pospolity, nieatrakcyjny", en: "plain" },
    { pl: "ładny", en: "pretty" },
    { pl: "brzydki", en: "ugly" },
    { pl: "ograniczać", en: "cut down on", tip: "ilość czegoś" },
    { pl: "wybierać, sięgać po", en: "go for", tip: "ciemniejsze kolory" },
    { pl: "malować paznokcie", en: "paint nails" },
    { pl: "przybierać/tracić", en: "put on/lose", tip: "na wadze" },
    { pl: "prostować", en: "straighten", tip: "włosy" },
    { pl: "zacząć", en: "take up", tip: "hobby, sport" },
    { pl: "gruby", en: "fat" },
    { pl: "umięśniony", en: "muscular" },
    { pl: "otyły", en: "obese" },
    { pl: "z nadwagą/z niedowagą", en: "overweight/underweight" },
    { pl: "puszysty/pulchny", en: "plump" },
    { pl: "chudy", en: "skinny" },
    { pl: "szczupły", en: "slim" },
    { pl: "dobrze zbudowany", en: "well-built" },
    { pl: "tyczkowaty, wysoki i chudy", en: "lanky" },
    { pl: "krępy", en: "stocky" },
    { pl: "łysy", en: "bald" },
    { pl: "blond", en: "blond" },
    { pl: "kręcone", en: "curly" },
    { pl: "ciemne", en: "dark" },
    { pl: "farbowane", en: "dyed" },
    { pl: "rude", en: "red" },
    { pl: "do ramion", en: "shoulder-length" },
    { pl: "proste", en: "straight", tip: "włosy" },
    { pl: "falujące", en: "wavy" },
    { pl: "kasztanowe", en: "auburn" },
    { pl: "cienkie, rzadkie/gęste", en: "fine/thick" },
    { pl: "grzywka", en: "fringe" },
    { pl: "mieć przedziałek na środku/z boku", en: "have a center/side parting" },
    { pl: "kita, koński, ogon", en: "ponytail" },
    { pl: "włosy rzednące na skroniach", en: "receding hairline" },
    { pl: "nosić włosy rozpuszczone/spięte", en: "wear your hair loose/up" },
    { pl: "broda", en: "beard" },
    { pl: "piegi", en: "freckles" },
    { pl: "wąsy", en: "moustache" },
    { pl: "blada/opalona/ciemna cera", en: "pale/tanned/dark complexion" },
    { pl: "przekłute uszy", en: "pierced ears" },
    { pl: "blizna", en: "scar" },
    { pl: "pryszczaty", en: "spotty" },
    { pl: "tatuaż", en: "tattoo" },
    { pl: "zmarszczki", en: "wrinkles" },
    { pl: "znamię", en: "birthmark" },
    { pl: "gładko ogolony", en: "clean-shaven" },
    { pl: "gładka skóra", en: "clear-skin" },
    { pl: "podwójny podbródek", en: "double chin" },
    { pl: "wystające kości policzkowe", en: "high cheekbones" },
    { pl: "wysokie czoło", en: "high forehead" },
    { pl: "przenikliwe niebieskie oczy", en: "piercing blue eyes" }
  ],
  c1s3: [
    { pl: "bluzka", en: "blouse" },
    { pl: "wysokie buty, kozaki", en: "boots" },
    { pl: "biustonosz", en: "bra" },
    { pl: "codzienny, swobodny", en: "casual" },
    { pl: "płaszcz", en: "coat" },
    { pl: "sukienka", en: "dress" },
    { pl: "modny", en: "fashionable/trendy" },
    { pl: "bluza polarowa", en: "fleece" },
    { pl: "rękawiczki", en: "gloves" },
    { pl: "kapelusz, czapka", en: "hat" },
    { pl: "kurtka, marynarka, żakiet", en: "jacket" },
    { pl: "dżinsy", en: "jeans" },
    { pl: "sweter", en: "jumper" },
    { pl: "staromodny, staroświecki", en: "old-fashioned" },
    { pl: "piżama", en: "pyjamas" },
    { pl: "sandały", en: "sandals" },
    { pl: "koszula", en: "shirt" },
    { pl: "buty", en: "shoes" },
    { pl: "szorty", en: "shorts" },
    { pl: "spódnica", en: "skirt" },
    { pl: "elegancki", en: "smart", tip: "strój" },
    { pl: "skarpety", en: "socks" },
    { pl: "garnitur", en: "suit" },
    { pl: "bluza sportowa", en: "sweatshirt" },
    { pl: "krawat", en: "tie" },
    { pl: "dres", en: "tracksuit" },
    { pl: "obuwie sportowe", en: "trainers" },
    { pl: "spodnie", en: "trousers" },
    { pl: "bielizna", en: "underwear" },
    { pl: "kamizelka", en: "waistcoat" },
    { pl: "nosić, mieć na sobie", en: "wear" },
    { pl: "suknia balowa, strój balowy", en: "ballgown" },
    { pl: "z szerokim dekoltem", en: "boat-necked" },
    { pl: "rozpinany sweter", en: "cardigan" },
    { pl: "kołnierzyk", en: "collar" },
    { pl: "mankiety", en: "cuffs" },
    { pl: "szlafrok", en: "dressing gown" },
    { pl: "wysokie obcasy", en: "high heels" },
    { pl: "bluza z kapturem", en: "hoodie" },
    { pl: "z długim/krótkim rękawem", en: "long/short-sleeved" },
    { pl: "bluzka bez ramiączek", en: "strapless top" },
    { pl: "dekolt w szpic", en: "V-neck" },
    { pl: "dodatki", en: "accessories" }
  ],
  c1s4: [
    { pl: "pasek", en: "belt" },
    { pl: "guzik", en: "button" },
    { pl: "czapka z daszkiem", en: "cap" },
    { pl: "kolczyki", en: "earrings" },
    { pl: "okulary", en: "glasses" },
    { pl: "torebka", en: "handbag/bag" },
    { pl: "biżuteria", en: "jewellery" },
    { pl: "naszyjnik", en: "necklace" },
    { pl: "pierścionek", en: "ring" },
    { pl: "szalik", en: "scarf" },
    { pl: "bransoletka", en: "bracelet" },
    { pl: "broszka", en: "brooch" },
    { pl: "sznurówki", en: "shoe laces" },
    { pl: "kapcie", en: "slippers" },
    { pl: "na zamek", en: "zip-up" },
    { pl: "w kratę", en: "checked" },
    { pl: "bawełna", en: "cotton" },
    { pl: "złoto", en: "gold" },
    { pl: "skóra, skórzany", en: "leather" },
    { pl: "gładki", en: "plain" },
    { pl: "jedwab", en: "silk" },
    { pl: "srebro, srebrny", en: "silver" },
    { pl: "w kropki", en: "spotted" },
    { pl: "w paski", en: "stripped" },
    { pl: "w szkocką kratę", en: "tartan" },
    { pl: "wełna", en: "wool" },
    { pl: "elastyczny", en: "elastic" },
    { pl: "futro, futrzany", en: "fur" },
    { pl: "koronkowy", en: "lacy" },
    { pl: "na doszewce, ocieplany", en: "lined" }
  ],
  c1s5: [
    { pl: "agresywny", en: "aggressive" },
    { pl: "ambitny", en: "ambitious" },
    { pl: "wybuchowy", en: "bad-tempered" },
    { pl: "zarozumiały", en: "big-headed" },
    { pl: "odważny", en: "brave" },
    { pl: "ostrożny/nieostrożny", en: "careful/careless" },
    { pl: "troskliwy", en: "caring" },
    { pl: "radosny, pogodny", en: "cheerful" },
    { pl: "mądry", en: "clever" },
    { pl: "pewny siebie/zbyt pewny siebie", en: "confident/overconfident" },
    { pl: "panikarz, osoba nadmiernie dramatyzująca", en: "drama queen" },
    { pl: "wyluzowany, opanowany", en: "easygoing" },
    { pl: "energiczny", en: "energetic" },
    { pl: "ekstrawertyk", en: "extrovert" },
    { pl: "przyjacielski, miły", en: "friendly" },
    { pl: "lubiący dobrą zabawę", en: "fun-loving" },
    { pl: "szczodry, hojny", en: "generous" },
    { pl: "delikatny, łagodny", en: "gentle" },
    { pl: "pracowity", en: "hard-working" },
    { pl: "uczynny/nieskory do pomocy", en: "helpful/unhelpful" },
    { pl: "uczciwy/nieuczciwy", en: "honest/dishonest" },
    { pl: "pomysłowy, kreatywny/bez wyobraźni", en: "imaginative/unimaginative" },
    { pl: "niezależny", en: "independent" },
    { pl: "inteligentny", en: "intelligent" },
    { pl: "introwertyk", en: "introvert" },
    { pl: "leniwy", en: "lazy" },
    { pl: "skąpy, złośliwy", en: "mean" },
    { pl: "bałaganiarski", en: "messy" },
    { pl: "złośliwy, wstrętny", en: "nasty" },
    { pl: "miły", en: "nice" },
    { pl: "otwarty", en: "open" },
    { pl: "optymistyczny", en: "optimistic" },
    { pl: "pesymistyczny", en: "pessimistic" },
    { pl: "otwarty, towarzyski", en: "outgoing" },
    { pl: "cierpliwy", en: "patient" },
    { pl: "niecierpliwy", en: "impatient" },
    { pl: "uprzejmy", en: "polite" },
    { pl: "cichy", en: "quiet" },
    { pl: "solidny, niezawodny/niesolidny, zawodny", en: "reliable/unreliable" },
    { pl: "odpowiedzialny", en: "responsible" },
    { pl: "niegrzeczny", en: "rude" },
    { pl: "samolubny/bezinteresowny", en: "selfish/unselfish" },
    { pl: "poważny", en: "serious" },
    { pl: "nieśmiały", en: "shy" },
    { pl: "niemądry, głupkowaty", en: "silly" },
    { pl: "towarzyski/nietowarzyski", en: "sociable/unsociable" },
    { pl: "gadatliwy, rozmowny", en: "talkative" },
    { pl: "schludny, porządny/niechlujny", en: "tidy/untidy" },
    { pl: "apodyktyczny", en: "bossy" },
    { pl: "tchórzliwy", en: "cowardly" },
    { pl: "ekscentryczny", en: "eccentric" },
    { pl: "materialistyczny", en: "materialistic" },
    { pl: "skromny", en: "modest" },
    { pl: "kapryśny", en: "moody" },
    { pl: "dziwny", en: "odd" },
    { pl: "dziwak", en: "oddball" },
    { pl: "wrażliwy", en: "sensitive" },
    { pl: "szczery", en: "sincere" },
    { pl: "życzliwy, współczujący", en: "sympathetic" },
    { pl: "dziwny", en: "weird" },
    { pl: "dziwak/dziwaczka, dziwadło", en: "weirdo" },
    { pl: "cudowne dziecko", en: "whizzkid" },
    { pl: "zamknięty w sobie", en: "withdrawn" },
  ],
  c1s6: [
    { pl: "zły, rozgniewany", en: "angry" },
    { pl: "zirytowany, rozdrażniony", en: "annoyed" },
    { pl: "być w dobrym/złym humorze", en: "be in a good/bad mood" },
    { pl: "znudzony", en: "bored" },
    { pl: "zły, rozgniewany", en: "cross" },
    { pl: "załamany, przygnębiony", en: "depressed" },
    { pl: "rozczarowany,zawiedziony", en: "disappointed" },
    { pl: "zawstydzony", en: "embarrassed" },
    { pl: "podekscytowany", en: "excited" },
    { pl: "wyczerpany, zmęczony", en: "exhausted" },
    { pl: "przerażony", en: "frightened" },
    { pl: "zdenerwowany, spięty", en: "nervous" },
    { pl: "zadowolony", en: "pleased" },
    { pl: "zrelaksowany", en: "relaxed" },
    { pl: "wystraszony", en: "scared" },
    { pl: "zszokowany", en: "shocked" },
    { pl: "zestresowany", en: "stressed" },
    { pl: "zdziwiony, zaskoczony", en: "surprised" },
    { pl: "zmęczony", en: "tired" },
    { pl: "przygnębiony, zaniepokojony", en: "upset" },
    { pl: "zmartwiony", en: "worried" },
    { pl: "zdumiony, zdziwiony", en: "amazed" },
    { pl: "zachwycony", en: "delighted" },
    { pl: "dręczące uczucie", en: "nagging feeling" },
    { pl: "przerażony", en: "petrified" },
    { pl: "zdruzgotany, wykończony", en: "shattered" },
    { pl: "oniemiały, osłupiały", en: "stunned" },
    { pl: "wycieńczony, wyczerpany", en: "worn out" },
  ],
  c1s7: [
    { pl: "uwielbiać", en: "adore" },
    { pl: "być fanem kogoś/czegoś", en: "be a fan of sb/sth" },
    { pl: "być beznadziejnym w", en: "be hopeless at" },
    { pl: "interesować się czymś", en: "be interested in sth" },
    { pl: "zajmować się czymś, interesować", en: "be into sth" },
    { pl: "interesować się, lubić coś robić", en: "be keen on sth" },
    { pl: "szaleć za kimś/czymś", en: "be mad about sb/sth" },
    { pl: "nie znosić", en: "can't stand" },
    { pl: "grać w gry/gry planszowe", en: "play games/board games" },
    { pl: "ćwiczyć", en: "work out" },
  ],
  c1s8: [
    { pl: "aborcja", en: "abortion" },
    { pl: "dobroczynność, organizacja charytatywna", en: "charity" },
    { pl: "zażywanie narkotyków", en: "drug abuse" },
    { pl: "sprawiedliwy handel", en: "fair trade" },
    { pl: "bezdomność", en: "homelessness" },
    { pl: "bezrobocie", en: "unemployment" },
    { pl: "korupcja", en: "corruption" },
    { pl: "rasizm", en: "racism" },
    { pl: "kara śmierci", en: "death penalty" },
    { pl: "eutanazja", en: "euthanasia" },
    { pl: "wolność słowa", en: "freedom of speech" },
    { pl: "hazard", en: "gambling" },
    { pl: "inżynieria genetyczna", en: "genetic engineering" },
    { pl: "prywatność", en: "privacy" },
  ],
  c1s9: [
    { pl: "krótki, krótkotrwały", en: "brief" },
    { pl: "wpaść na, natknąć się na", en: "come across" },
    { pl: "całkowity, kompletny", en: "complete" },
    { pl: "rozwinąć się w, stawać się", en: "develop into", tip: "kimś" },
    { pl: "fanatyk/fanatyczka ekologii", en: "eco-freak" },
    { pl: "fanatyk/fanatyczka ćwiczeń fizycznych", en: "fitness maniac" },
    { pl: "skupiać się na", en: "focus on" },
    { pl: "rosnąć, dorastać", en: "grow up" },
    { pl: "mieć dużo/niewiele wspólnego", en: "have a lot/little in common" },
    { pl: "osoba mająca obsesję na punkcie zdrowia", en: "health nut" },
    { pl: "ogromny", en: "huge" },
    { pl: "zidentyfikować", en: "identify" },
    { pl: "podziwiać", en: "look up to" },
    { pl: "zdać sobie sprawę", en: "realise" },
    { pl: "rozpoznać", en: "recognise" },
    { pl: "pamiętać", en: "remember" },
    { pl: "przypomnieć komuś, by coś zrobił", en: "remind someone to do something" },
    { pl: "wydawać pieniądze na", en: "spend money on" },
    { pl: "dostrzec", en: "spot" },
    { pl: "całkowite przeciwieństwo", en: "the complete opposite" },
    { pl: "typowy dla", en: "typical of" },
    { pl: "leżeć w czyjejś naturze", en: "be part of someone's nature" },
    { pl: "zaprzyjaźnić się z", en: "befriend" },
    { pl: "dziwny", en: "bizarre" },
    { pl: "nie móc uwierzyć własnym uszom", en: "can't believe your ears" },
    { pl: "częste doznanie", en: "common experience" },
    { pl: "znaleźć wspólną płaszczyznę", en: "find common ground" },
    { pl: "doskonale się bawić", en: "have the time of your life" },
    { pl: "rozpoznać, zidentyfikować", en: "place" },
    { pl: "zdobyć się na odwagę", en: "pluck up the courage", tip: "aby coś zrobić" },
    { pl: "nasuwać pytania", en: "raise questions" },
    { pl: "przeskanować, przebiec wzrokiem", en: "scan", tip: "mózg, tekst" },
    { pl: "skomplikowany, zaawansowany", en: "sophisticated" },
    { pl: "nawiązać", en: "strike up", tip: "konwersację" }
  ],
  c2s1: [
    { pl: "blok mieszkalny", en: "block of flats" },
    { pl: "budynek", en: "building" },
    { pl: "dom parterowy", en: "bungalow" },
    { pl: "zamek", en: "castle" },
    { pl: "domek wiejski", en: "cottage" },
    { pl: "wolno stojący dom jednorodzinny", en: "detached house" },
    { pl: "dom rodzinny", en: "family home" },
    { pl: "dom w gospodarstwie rolnym", en: "farmhouse" },
    { pl: "mieszkanie", en: "flat" },
    { pl: "dom", en: "house" },
    { pl: "pałac, rezydencja", en: "mansion" },
    { pl: "dom spokojnej starości", en: "nursing home" },
    { pl: "bliźniak", en: "semi-detached house" },
    { pl: "kawalerka", en: "studio flat" },
    { pl: "dom szeregowy, segment", en: "terraced house" },
    { pl: "wieżowiec", en: "tower block" },
    { pl: "willa", en: "villa" },
    { pl: "domy, mieszkania w przystępnej cenie", en: "affordable housing" },
    { pl: "wszystkie wygody", en: "all mod cons" },
    { pl: "aukcja, licytacja", en: "auction" },
    { pl: "kawalerka do wynajęcia", en: "bedsit" },
    { pl: "oferta w licytacji", en: "bid" },
    { pl: "zniszczony, walący się", en: "dilapidated" },
    { pl: "osiedle mieszkaniowe", en: "housing estate" },
    { pl: "do remontu", en: "in need of renovation" },
    { pl: "przyczepa mieszkalna", en: "mobile home" },
    { pl: "mieszkanie dla emeryta", en: "retirement flat" },
    { pl: "mieszkania dla osób wymagających opieki", en: "sheltered accommodation" },
    { pl: "w budowie", en: "under construction" }
  ],
  c2s2: [
    { pl: "z dala od", en: "away from" },
    { pl: "miasto", en: "city" },
    { pl: "dojeżdżać", en: "commute", tip: "do pracy lub do szkoły" },
    { pl: "dzielnica", en: "district" },
    { pl: "w wiejskiej okolicy", en: "in a rural area" },
    { pl: "w centrum", en: "in the centre" },
    { pl: "na wsi", en: "in the countryside" },
    { pl: "na przedmieściach", en: "in the suburbs" },
    { pl: "mieszkaniec/mieszkanka", en: "inhabitant" },
    { pl: "położony", en: "located" },
    { pl: "sąsiad/sąsiadka", en: "neighbour" },
    { pl: "sąsiedztwo, okolica", en: "neighbourhood" },
    { pl: "stare miasto", en: "Old Town" },
    { pl: "na skraju", en: "on the edge of" },
    { pl: "wychodzić na, mieć widok na", en: "overlook" },
    { pl: "transport publiczny", en: "public transport" },
    { pl: "mieszkańcy", en: "residents" },
    { pl: "widok", en: "view" },
    { pl: "wioska", en: "village" },
    { pl: "rzut kamieniem od", en: "a stone's throw from" },
    { pl: "po drugiej stronie ulicy", en: "across the road from" },
    { pl: "udogodnienia", en: "amenities" },
    { pl: "centralne położenie", en: "central location" },
    { pl: "zgiełk", en: "hustle and bustle" },
    { pl: "na głębokiej wsi", en: "in the heart of the countryside" },
    { pl: "na odludziu, w szczerym polu", en: "in the middle of nowhere" },
    { pl: "na uboczu", en: "off the beaten track" },
    { pl: "w bliskiej odległości", en: "within walking distance of", tip: "możliwej do pokonania pieszo" }
  ],
  c2s3: [
    { pl: "strych, poddasze", en: "attic" },
    { pl: "balkon", en: "balcony" },
    { pl: "piwnica", en: "basement/cellar" },
    { pl: "łazienka", en: "bathroom" },
    { pl: "sypialnia", en: "bedroom" },
    { pl: "wiata na samochód", en: "carport" },
    { pl: "sufit", en: "ceiling" },
    { pl: "komin", en: "chimney" },
    { pl: "jadalnia", en: "dining room" },
    { pl: "drzwi", en: "door" },
    { pl: "na dole, na parter", en: "downstairs" },
    { pl: "podjazd", en: "drive" },
    { pl: "ogrodzenie, płot", en: "fence" },
    { pl: "kominek", en: "fireplace" },
    { pl: "przednie/tylne drzwi", en: "front/back door" },
    { pl: "garaż", en: "garage" },
    { pl: "ogród", en: "garden" },
    { pl: "brama", en: "gate" },
    { pl: "parter", en: "ground floor" },
    { pl: "hol", en: "hall" },
    { pl: "żywopłot", en: "hedge" },
    { pl: "wyspa kuchenna", en: "island" },
    { pl: "kuchnia", en: "kitchen" },
    { pl: "domowa pralnia", en: "laundry room" },
    { pl: "winda", en: "lift" },
    { pl: "pokój dzienny/salon", en: "living room/lounge" },
    { pl: "strych, poddasze", en: "loft" },
    { pl: "ganek", en: "porch" },
    { pl: "dach", en: "roof" },
    { pl: "szopa", en: "shed" },
    { pl: "pokój dzienny", en: "sitting room" },
    { pl: "schody/klatka schodowa", en: "stairs/staircase" },
    { pl: "schodki", en: "steps" },
    { pl: "gabinet", en: "study" },
    { pl: "na górze, na piętrze", en: "upstairs" },
    { pl: "ściana, mur", en: "wall" },
    { pl: "alarm antywłamaniowy", en: "burglar alarm" },
    { pl: "z podwójną szybą", en: "double-glazed" },
    { pl: "przybudówka", en: "extension" },
    { pl: "staw rybny", en: "fish pond" },
    { pl: "deski podłogowe", en: "floorboards" },
    { pl: "klomb", en: "flowerbed" },
    { pl: "półpiętro", en: "landing" },
    { pl: "alarm przeciwpożarowy", en: "smoke alarm" },
    { pl: "panele słoneczne", en: "solar panels" },
    { pl: "poręcz przy schodach", en: "stair rail" },
    { pl: "pomieszczenie gospodarcze", en: "utility room" },
    { pl: "parapet okienny", en: "windowsill" }
  ],
  c2s4: [
    { pl: "przestronny", en: "airy/spacious" },
    { pl: "cegła", en: "brick" },
    { pl: "jasny", en: "bright" },
    { pl: "zagracony", en: "cluttered" },
    { pl: "wygodny", en: "comfortable" },
    { pl: "przerobić, przekształcić", en: "convert" },
    { pl: "przytulny", en: "cosy/homely" },
    { pl: "wykończony, odnowiony", en: "decorated" },
    { pl: "przyjazny dla środowiska", en: "eco-friendly" },
    { pl: "umeblowany/nieumeblowany", en: "furnished/unfurnished" },
    { pl: "szkło, szklany", en: "glass" },
    { pl: "luksusowy", en: "luxurious" },
    { pl: "utrzymywać, konserwować", en: "maintain" },
    { pl: "nowoczesny", en: "modern" },
    { pl: "błoto", en: "mud" },
    { pl: "używany, z drugiej ręki", en: "second-hand" },
    { pl: "stalowy", en: "steel" },
    { pl: "kamienny", en: "stone" },
    { pl: "posprzątany/nieposprzątany", en: "tidy/untidy" },
    { pl: "drewniany", en: "wooden" },
    { pl: "źle wykończony", en: "badly-decorated" },
    { pl: "ciasny", en: "cramped" },
    { pl: "zakurzony", en: "dusty" },
    { pl: "dębowy", en: "oak" },
    { pl: "staromodny", en: "old-fashioned" },
    { pl: "bez ścian działowych", en: "open-plan" },
    { pl: "duszny", en: "stuffy" },
    { pl: "o unikalnym wyglądzie", en: "unique-looking" },
    { pl: "dobrze utrzymany, zadbany", en: "well-maintained" },
    { pl: "meble", en: "furniture" },
  ],
  c2s5: [
    { pl: "budzik", en: "alarm clock" },
    { pl: "fotel", en: "armchair" },
    { pl: "wanna", en: "bath" },
    { pl: "łóżko", en: "bed" },
    { pl: "stolik nocny", en: "bedside table" },
    { pl: "kosz", en: "bin" },
    { pl: "koc", en: "blanket" },
    { pl: "rolety", en: "blinds" },
    { pl: "biblioteczka", en: "bookcase" },
    { pl: "półka/półki na książki", en: "bookshelf/bookshelves" },
    { pl: "dywan", en: "carpet" },
    { pl: "odtwarzacz płyt CD", en: "CD player" },
    { pl: "centralne ogrzewanie", en: "central heating" },
    { pl: "krzesło, fotel", en: "chair" },
    { pl: "komoda", en: "chest of drawers" },
    { pl: "kuchenka", en: "cooker" },
    { pl: "szafka kuchenna", en: "cupboard" },
    { pl: "zasłony/firanki", en: "curtains/net curtains" },
    { pl: "poduszka", en: "cushion", tip: "dekoracyjna" },
    { pl: "biurko", en: "desk" },
    { pl: "zmywarka", en: "dishwasher" },
    { pl: "podwójne łóżko", en: "double bed" },
    { pl: "kołdra", en: "duvet" },
    { pl: "wyposażenie, sprzęt", en: "equipment" },
    { pl: "wykładzina dywanowa", en: "fitted carpet" },
    { pl: "doniczka", en: "flowerpot" },
    { pl: "zamrażarka", en: "freezer" },
    { pl: "lodówka", en: "fridge" },
    { pl: "odkurzacz", en: "hoover" },
    { pl: "lampa", en: "lamp" },
    { pl: "światło", en: "light" },
    { pl: "oświetlenie", en: "lighting" },
    { pl: "kuchenka mikrofalowa", en: "microwave" },
    { pl: "lustro", en: "mirror" },
    { pl: "piekarnik", en: "oven" },
    { pl: "obrazek", en: "picture" },
    { pl: "poduszka", en: "pillow" },
    { pl: "plakat", en: "poster" },
    { pl: "kaloryfer", en: "radiator" },
    { pl: "dywanik", en: "rug" },
    { pl: "prześcieradło", en: "sheet" },
    { pl: "półka", en: "shelf" },
    { pl: "prysznic", en: "shower" },
    { pl: "pojedyncze łóżko", en: "single bed" },
    { pl: "zlew", en: "sink" },
    { pl: "kanapa", en: "sofa" },
    { pl: "stół", en: "table" },
    { pl: "toster", en: "toaster" },
    { pl: "toaleta, sedes", en: "toilet" },
    { pl: "telewizor", en: "TV set" },
    { pl: "tapeta", en: "wallpaper" },
    { pl: "szafa", en: "wardrobe" },
    { pl: "umywalka", en: "washbasin" },
    { pl: "pralka", en: "washing machine" },
    { pl: "zabytkowy, staroświecki", en: "antique" },
    { pl: "miska na owoce", en: "fruit bowl" },
    { pl: "wskazówka", en: "hand", tip: "zegara" },
    { pl: "czajnik", en: "kettle" },
    { pl: "sprzęt kuchenny", en: "kitchen appliances" },
    { pl: "przybory kuchenne", en: "kitchen utensils" },
    { pl: "półka nad kominkiem", en: "mantelpiece" },
    { pl: "ozdoba", en: "ornament" },
    { pl: "roślina doniczkowa", en: "potted plant" },
    { pl: "okiennice", en: "shutters" },
    { pl: "srebrna ramka", en: "silver frame" },
    { pl: "półka, stojak", en: "rack" }
  ],
  c2s6: [
    { pl: "gospodarstwo domowe", en: "household" },
    { pl: "zmienić pościel", en: "change the sheets" },
    { pl: "pracować w ogrodzie", en: "do the gardening" },
    { pl: "zajmować się domem", en: "do the housework" },
    { pl: "opróżniać zmywarkę", en: "empty the dishwasher" },
    { pl: "mieć dobrą rękę do roślin", en: "have green fingers" },
    { pl: "odkurzać dywan", en: "hoover the carpet" },
    { pl: "prasować ubrania", en: "iron the clothes" },
    { pl: "ścielić łóżko", en: "make the bed" },
    { pl: "kosić trawnik", en: "mow the lawn" },
    { pl: "zamiatać podłogę", en: "sweep the floor" },
    { pl: "porządkować biurko", en: "tidy the desk" },
    { pl: "miotła", en: "broom" },
    { pl: "szczotka", en: "brush" },
    { pl: "ściereczka do kurzu", en: "duster" },
    { pl: "kosiarka", en: "lawnmower" },
    { pl: "grabie", en: "rake" },
    { pl: "gumowe rękawiczki", en: "rubber gloves" },
    { pl: "szpadel", en: "spade" },
    { pl: "rydel", en: "trowel" }
  ],
  c2s7: [
    { pl: "zakwaterowanie", en: "accommodation" },
    { pl: "ogłoszenie, reklama", en: "ad/advert" },
    { pl: "współlokator/współlokatorka", en: "roommate/flatmate/housemate" },
    { pl: "na sprzedaż", en: "for sale" },
    { pl: "właściciel/właścicielka", en: "landlord/landlady", tip: "mieszkania lub domu" },
    { pl: "mieszkać samemu", en: "live on one's own" },
    { pl: "wprowadzić się/wyprowadzić się", en: "move in/move out" },
    { pl: "zapłacić z góry", en: "pay in advance" },
    { pl: "wynająć, czynsz", en: "rent" },
    { pl: "dzielić z kimś pokój/mieszkanie/dom", en: "share a room/flat/house" },
    { pl: "do wynajęcia", en: "to let" },
    { pl: "rachunek", en: "bill" },
    { pl: "budżet", en: "budget" },
    { pl: "liczyć, pobierać opłatę", en: "charge" },
    { pl: "kaucja, zaliczka", en: "deposit" },
    { pl: "agent/agentka nieruchomości", en: "estate agent" },
    { pl: "parapetówka", en: "housewarming" },
    { pl: "raty", en: "installments" },
    { pl: "wypowiedzenie", en: "notice" },
    { pl: "płatność", en: "payment" },
    { pl: "tygodniowo/miesięcznie", en: "per week/per month" },
    { pl: "wziąć kredyt hipoteczny", en: "take out a mortgage" },
    { pl: "najemca, lokator", en: "tenant" }
  ],
  c2s8: [
    { pl: "w przystępnej cenie", en: "affordable" },
    { pl: "poza", en: "beyond" },
    { pl: "skarżyć się, narzekać", en: "complain" },
    { pl: "upiększyć, podkolorować", en: "embellish" },
    { pl: "w pełni umeblowany", en: "fully furnished" },
    { pl: "nie spuszczać z oczu", en: "keep your eyes on", tip: "kogoś/czegoś" },
    { pl: "tęsknić za", en: "miss" },
    { pl: "w pobliżu, pobliski", en: "nearby" },
    { pl: "niebezpieczny", en: "rough" },
    { pl: "ostry", en: "sharp" },
    { pl: "wzdychać, westchnienie", en: "sigh" },
    { pl: "wpatrywać się w", en: "stare at" },
    { pl: "dąsać się", en: "sulk" },
    { pl: "maleńki, niewielki", en: "tiny" },
    { pl: "być szalonym", en: "be off your head" },
    { pl: "nieostry, zamazany", en: "blurry" },
    { pl: "wpaść na kogoś, spotkać kogoś przypadkiem", en: "bump into" },
    { pl: "wsiąść", en: "get into" },
    { pl: "zrobić awanturę", en: "kick up a fuss" },
    { pl: "pełen zakamarków", en: "rambling" },
    { pl: "zniszczony, podupadły", en: "run-down" },
    { pl: "przytulny, zaciszny", en: "snug" },
    { pl: "samotność", en: "solitude" },
    { pl: "wciśnięty", en: "squashed" },
    { pl: "plama", en: "stain" },
    { pl: "wlewać się", en: "stream in" },
    { pl: "natknąć się na", en: "stumble upon" },
    { pl: "zmienić się w, przeobrazić się w", en: "turn into" },
    { pl: "pojawić się na", en: "turn up for" },
    { pl: "pochłonięty czymś", en: "wrapped up in" }
  ],
  c3s1: [
    { pl: "przedmioty artystyczne", en: "arts subjects" },
    { pl: "biologia", en: "biology" },
    { pl: "chemia", en: "chemistry" },
    { pl: "podwójna lekcja", en: "double lesson" },
    { pl: "języki obce", en: "foreign languages" },
    { pl: "geografia", en: "geography" },
    { pl: "nauki humanistyczne", en: "humanities" },
    { pl: "historia", en: "history" },
    { pl: "informatyka", en: "IT/information technology" },
    { pl: "matematyka/matma", en: "mathematics/maths" },
    { pl: "muzyka", en: "music" },
    { pl: "WF, wychowanie fizyczne", en: "PE/physical education" },
    { pl: "fizyka", en: "physics" },
    { pl: "język polski", en: "Polish" },
    { pl: "religia", en: "religious education" },
    { pl: "przedmioty ścisłe", en: "science subjects" },
    { pl: "nauki społeczne", en: "social sciences" },
    { pl: "technika", en: "design and technology" },
    { pl: "ekonomia", en: "economic education" },
    { pl: "nauka o ochronie środowiska", en: "environmental science" },
    { pl: "medioznawstwo", en: "media studies" },
    { pl: "psychologia sportu", en: "sports psychology" }
  ],
  c3s2: [
    { pl: "oszukiwać, ściągać", en: "cheat" },
    { pl: "przepisać, skopiować", en: "copy" },
    { pl: "wkuwać", en: "cram" },
    { pl: "dyplom", en: "diploma" },
    { pl: "egzamin semestralny", en: "end-of-term/year exam", tip: "na koniec roku" },
    { pl: "arkusz egzaminacyjny", en: "exam paper" },
    { pl: "egzamin", en: "examination" },
    { pl: "dodatkowe lekcje", en: "extra lessons" },
    { pl: "podejść do egzaminu", en: "take an exam" },
    { pl: "oblać", en: "fail" },
    { pl: "egzamin końcowy", en: "final exam" },
    { pl: "zostać złapanym", en: "get caught" },
    { pl: "otrzymać wyniki", en: "get results" },
    { pl: "wystawiać oceny", en: "give marks" },
    { pl: "składać się na", en: "go towards" },
    { pl: "ocena", en: "grade/mark" },
    { pl: "uczyć się na pamięć", en: "memorise" },
    { pl: "egzamin próbny", en: "mock/practice exam" },
    { pl: "ustny", en: "oral" },
    { pl: "zdać", en: "pass" },
    { pl: "arkusz egzaminacyjny z poprzednich lat", en: "past paper" },
    { pl: "praktyczny", en: "practical" },
    { pl: "zdawać ponownie", en: "retake" },
    { pl: "powtarzać do", en: "revise for" },
    { pl: "egzamin kończący naukę w szkole", en: "school-leaving exam" },
    { pl: "wysyłać", en: "send out" },
    { pl: "podejść do testu", en: "take a test" },
    { pl: "pisemny", en: "written" },
    { pl: "brytyjski odpowiednik matury", en: "A levels" },
    { pl: "wyniki w nauce", en: "academic results" },
    { pl: "nagroda; nagrodzić", en: "award" },
    { pl: "licencjat na kierunku humanistycznym", en: "BA/Bachelor of Arts" },
    { pl: "magister nauk humanistycznych", en: "MA/Master of Arts" },
    { pl: "licencjat w dziedzinie nauk ścisłych/przyrodniczych", en: "BSc/Bachelor of Science" },
    { pl: "świadectwo", en: "certificate" },
    { pl: "wyróżnienie", en: "distinction" },
    { pl: "brytyjski odpowiednik egzaminu gimnazjalnego", en: "GCSEs" },
    { pl: "otrzymać stopień naukowy", en: "get a degree" },
    { pl: "absolwent/absolwentka studiów", en: "graduate" },
    { pl: "ukończyć", en: "graduate from", tip: "studia wyższe" },
    { pl: "matura międzynarodowa", en: "International Baccalaureate" },
    { pl: "zdać celująco, śpiewająco", en: "pass with flying colours" },
    { pl: "z trudem przebrnąć", en: "scrape through", tip: "przez egzamin" },
    { pl: "zdobyć stypendium", en: "win a scholarship" }
  ],
  c3s3: [
    { pl: "nieobecny", en: "absent" },
    { pl: "dzwonek", en: "bell" },
    { pl: "przerwa", en: "break" },
    { pl: "dręczyć, prześladować", en: "bully" },
    { pl: "sprawdzić pracę", en: "check work" },
    { pl: "skupić się", en: "concentrate" },
    { pl: "podręcznik", en: "coursebook" },
    { pl: "praca okresowa", en: "coursework" },
    { pl: "program nauczania", en: "curriculum" },
    { pl: "termin wykonania pracy", en: "deadline" },
    { pl: "dyktando", en: "dictation" },
    { pl: "odrabiać lekcje", en: "do your homework" },
    { pl: "poszukiwać informacji, prowadzić badania", en: "do research" },
    { pl: "wykonać/napisać zadaną pracę", en: "do/write an assignment" },
    { pl: "napisać wypracowanie, esej", en: "do/write an essay" },
    { pl: "zostać zawieszonym", en: "get suspended" },
    { pl: "przedstawić prezentację", en: "give a presentation" },
    { pl: "przedstawić referat na temat", en: "give a talk on" },
    { pl: "oddawać pracę domową", en: "hand in homework" },
    { pl: "przerwa na lunch", en: "lunch break" },
    { pl: "styl uczenia się", en: "learning style" },
    { pl: "robić błędy", en: "make mistakes" },
    { pl: "opuszczać lekcje", en: "miss lessons" },
    { pl: "motywować; motywujący", en: "motivate" },
    { pl: "zeszyt", en: "notebook" },
    { pl: "drugie śniadanie", en: "packed lunch" },
    { pl: "strój sportowy", en: "PE kit" },
    { pl: "wagarować", en: "play truant" },
    { pl: "prezentować; obecny", en: "present" },
    { pl: "praca projektowa", en: "project work" },
    { pl: "zgłosić kogoś, donieść na kogoś", en: "report someone" },
    { pl: "zadawać pracę", en: "set homework" },
    { pl: "zwolnienie", en: "sick note", tip: "z powodu choroby" },
    { pl: "autobus szkolny", en: "school bus" },
    { pl: "rok szkolny", en: "school year" },
    { pl: "zrobić sobie rok przerwy między szkołą a studiami", en: "take a gap year" },
    { pl: "robić notatki", en: "take notes" },
    { pl: "semestr", en: "term" },
    { pl: "plan zajęć", en: "timetable" },
    { pl: "pracować nad projektem", en: "work on a project" },
    { pl: "pracować w parach", en: "work in pairs" },
    { pl: "osoba nieobecna", en: "absentee" },
    { pl: "absencja", en: "absenteeism" },
    { pl: "zgromadzenie, apel", en: "assembly" },
    { pl: "obecność na zajęciach, frekwencja", en: "attendance" },
    { pl: "obowiązkowy", en: "compulsory" },
    { pl: "czas skupienia uwagi", en: "concentration span" },
    { pl: "urwać się z lekcji", en: "cut classes" },
    { pl: "kara - zostanie po lekcjach", en: "detention" },
    { pl: "podrabiać", en: "forge" },
    { pl: "wolna lekcja", en: "free period" },
    { pl: "obligatoryjny, obowiązkowy", en: "obligatory" },
    { pl: "były uczeń/była uczennica", en: "old student" },
    { pl: "opcjonalny, dobrowolny", en: "optional" },
    { pl: "rozdanie nagród", en: "prize-giving" },
    { pl: "punktualność", en: "punctuality" },
    { pl: "sprawdzać obecność", en: "take the register" },
    { pl: "wziąć wolne", en: "take time off" },
    { pl: "konsultacje", en: "tutorial" }
  ],
  c3s4: [
    { pl: "woźny/woźna", en: "caretaker" },
    { pl: "kolega/koleżanka z klasy", en: "classmate" },
    { pl: "asystent/asystentka nauczyciela", en: "classroom assistant" },
    { pl: "wychowawca/ wychowawczyni", en: "form tutor" },
    { pl: "dyrektor/dyrektorka szkoły", en: "head teacher", tip: "nieoficjalnie" },
    { pl: "dyrektor/dyrektorka szkoły", en: "headmaster/headmistress", tip: "oficjalnie" },
    { pl: "uczeń/uczennica", en: "pupil" },
    { pl: "grono pedagogiczne", en: "staff" },
    { pl: "uczeń/uczennica, student/ studentka", en: "student" },
    { pl: "nauczyciel/nauczycielka", en: "teacher" },
    { pl: "doradca zawodowy", en: "careers adviser" },
    { pl: "wicedyrektor/wicedyrektorka", en: "deputy head" },
    { pl: "przewodniczący/przewodnicząca szkoły", en: "head girl/head boy" },
    { pl: "wykładowca", en: "lecturer" },
    { pl: "gospodarz, przewodniczący klasy", en: "prefect" }
  ],
  c3s5: [
    { pl: "stołówka, bufet", en: "canteen" },
    { pl: "sala lekcyjna", en: "classroom" },
    { pl: "świetlica", en: "common room" },
    { pl: "korytarz", en: "corridor" },
    { pl: "sala gimnastyczna", en: "gymnasium" },
    { pl: "gabinet dyrektora szkoły", en: "head teacher's office" },
    { pl: "pracownia/laboratorium", en: "laboratory", tip: "fizyczna lub chemiczna" },
    { pl: "biblioteka", en: "library" },
    { pl: "boisko, plac zabaw", en: "playground" },
    { pl: "boisko", en: "sports field" },
    { pl: "pokój nauczycielski", en: "staffroom" },
    { pl: "aula", en: "lecture theatre" }
  ],
  c3s6: [
    { pl: "uczęszczać na kurs", en: "attend a course" },
    { pl: "należeć do", en: "belong to" },
    { pl: "impreza charytatywna", en: "charity event" },
    { pl: "klub", en: "club" },
    { pl: "wycieczka w ramach wymiany międzyszkolnej", en: "exchange trip" },
    { pl: "zajęcia pozalekcyjne", en: "extracurricular activities" },
    { pl: "impreza w celu zbierania funduszy", en: "fundraising event" },
    { pl: "brać udział w", en: "take part in" },
    { pl: "wstąpić do klubu/stowarzyszenia", en: "join a club/a society" },
    { pl: "członek/członkini", en: "member" },
    { pl: "uważać", en: "pay attention" },
    { pl: "wycieczka szkolna", en: "school trip" },
    { pl: "kółko", en: "society" },
    { pl: "obóz letni", en: "summer camp" },
    { pl: "szkolenie", en: "training" },
    { pl: "wolontariat", en: "voluntary work" }
  ],
  c3s7: [
    { pl: "uczelnia", en: "academy" },
    { pl: "szkoła koedukacyjna", en: "coeducational school" },
    { pl: "kolegium, szkoła pomaturalna", en: "college" },
    { pl: "szkoła ogólnokształcąca dla wszystkich", en: "comprehensive school", tip: "niezalenie od wyników w nauce" },
    { pl: "uczyć się zawodu", en: "do vocational training" },
    { pl: "szkoła podstawowa", en: "elementary school" },
    { pl: "szkoła średnia przyjmująca uczniów, którzy zdali egzamin wstępny", en: "grammar school" },
    { pl: "szkoła średnia", en: "high school" },
    { pl: "szkoła prywatna", en: "independent school" },
    { pl: "w USA szkoła średnia dla uczniów 13-15 lat", en: "junior high school" },
    { pl: "przedszkole", en: "kindergarten" },
    { pl: "żłobek", en: "nursery" },
    { pl: "szkoła podstawowa", en: "primary school" },
    { pl: "szkoła prywatna", en: "private school" },
    { pl: "szkoła średnia", en: "secondary school" },
    { pl: "szkoła żeńska/męska", en: "single-sex school" },
    { pl: "szkoła państwowa", en: "state school" },
    { pl: "uniwersytet", en: "university" },
    { pl: "szkoła z internatem", en: "boarding school" },
    { pl: "sieć szkół prywatnych", en: "public school system" },
    { pl: "czesne", en: "school fees" },
    { pl: "odbyć praktyki", en: "serve an apprenticeship" },
    { pl: "dzielić uczniów na grupy", en: "stream", tip: "ze względu na umiejętności" },
    { pl: "warsztat", en: "workshop" }
  ],
  c3s8: [
    { pl: "zaniepokojony", en: "concerned" },
    { pl: "zdezorientowany", en: "confused" },
    { pl: "rozczarowany", en: "disappointed" },
    { pl: "wydobyć, uzyskać", en: "elicit" },
    { pl: "podkreślić", en: "emphasise" },
    { pl: "narzucić, wymusić", en: "enforce" },
    { pl: "zapewnić, upewnić się", en: "ensure" },
    { pl: "znajomy", en: "familiar" },
    { pl: "przerażony", en: "frightened" },
    { pl: "pod wrażeniem", en: "impressed" },
    { pl: "na korzyść, za", en: "in favour of", tip: "czegoś" },
    { pl: "uwolnić", en: "let loose" },
    { pl: "spełnić oczekiwania", en: "live up to expectations" },
    { pl: "stracić rachubę", en: "lose count of", tip: "czegoś" },
    { pl: "szaleniec, maniak", en: "maniac" },
    { pl: "wprowadzić plan w życie", en: "put a plan into action" },
    { pl: "ceny, stawki", en: "rates" },
    { pl: "duszny", en: "stuffy" },
    { pl: "przeciwległy koniec", en: "the far end" },
    { pl: "o wiele za", en: "way too" },
    { pl: "powierzchnia robocza", en: "work surface" },
    { pl: "nie móc się zdecydować", en: "be in two minds about" },
    { pl: "zaspokajać", en: "cater for" },
    { pl: "pragnąć", en: "crave" },
    { pl: "opustoszały, bezludny", en: "deserted" },
    { pl: "podjechać", en: "draw up" },
    { pl: "skończyć", en: "end up", tip: "gdzieś, jako ktoś)" },
    { pl: "bezpośrednia komunikacja", en: "face-to-face communication", tip: "twarzą w twarz" },
    { pl: "oczekując", en: "in anticipation of", tip: "na coś" },
    { pl: "utrzymywać", en: "maintain" },
    { pl: "technika ułatwiająca zapamiętywanie", en: "memory aid" },
    { pl: "przemówienie motywacyjne", en: "motivational speech" },
    { pl: "optować za/wybrać", en: "opt for" },
    { pl: "prześcignąć, pozostawić w tyle", en: "outperform" },
    { pl: "zespół, ława", en: "panel" },
    { pl: "wysilać się, usiłować", en: "struggle" },
    { pl: "dzielić na mniejsze grupy", en: "subdivide" },
    { pl: "cenny, ceniony", en: "treasured" },
    { pl: "głosować nogami", en: "vote with your feet" }
  ],
  c4s1: [
    { pl: "x", en: "x" },
  ],
  c4s2: [
    { pl: "x", en: "x" },
  ],
  c4s3: [
    { pl: "x", en: "x" },
  ],
  c4s4: [
    { pl: "x", en: "x" },
  ],
  c4s5: [
    { pl: "x", en: "x" },
  ],
  c5s1: [
    { pl: "x", en: "x" },
  ],
  c5s2: [
    { pl: "x", en: "x" },
  ],
  c5s3: [
    { pl: "x", en: "x" },
  ],
  c5s4: [
    { pl: "x", en: "x" },
  ],
  c5s5: [
    { pl: "x", en: "x" },
  ],
  c5s6: [
    { pl: "x", en: "x" },
  ],
  c5s7: [
    { pl: "x", en: "x" },
  ],

  // Add more questions as needed
};

// cxs1: [
//   { pl: "x", en: "x" },
// ],
// cxs2: [
//   { pl: "x", en: "x" },
// ],
// cxs3: [
//   { pl: "x", en: "x" },
// ],
// cxs4: [
//   { pl: "x", en: "x" },
// ],
// cxs5: [
//   { pl: "x", en: "x" },
// ],
// cxs6: [
//   { pl: "x", en: "x" },
// ],
// cxs7: [
//   { pl: "x", en: "x" },
// ],