[
  { pl: "agresywny", en: "aggressive" },
  { pl: "ambitny", en: "ambitious" },
  { pl: "wybuchowy", en: "bad-tempered" },
  { pl: "zarozumiały", en: "big-headed" },
  { pl: "odważny", en: "brave" },
  { pl: "ostrożny/nieostrożny", en: "careful/careless" },
  { pl: "troskliwy", en: "caring" },
  { pl: "radosny, pogodny", en: "cheerful" },
  { pl: "mądry", en: "clever" },
  { pl: "pewny siebie/zbyt pewny siebie", en: "confident/overconfident" },
  { pl: "panikarz, osoba nadmiernie dramatyzująca", en: "drama queen" },
  { pl: "wyluzowany, opanowany", en: "easygoing" },
  { pl: "energiczny", en: "energetic" },
  { pl: "ekstrawertyk", en: "extrovert" },
  { pl: "przyjacielski, miły", en: "friendly" },
  { pl: "lubiący dobrą zabawę", en: "fun-loving" },
  { pl: "szczodry, hojny", en: "generous" },
  { pl: "delikatny, łagodny", en: "gentle" },
  { pl: "pracowity", en: "hard-working" },
  { pl: "uczynny/nieskory do pomocy", en: "helpful/unhelpful" },
  { pl: "uczciwy/nieuczciwy", en: "honest/dishonest" },
  { pl: "pomysłowy, kreatywny/bez wyobraźni", en: "imaginative/unimaginative" },
  { pl: "niezależny", en: "independent" },
  { pl: "inteligentny", en: "intelligent" },
  { pl: "introwertyk", en: "introvert" },
  { pl: "leniwy", en: "lazy" },
  { pl: "skąpy, złośliwy", en: "mean" },
  { pl: "bałaganiarski", en: "messy" },
  { pl: "złośliwy, wstrętny", en: "nasty" },
  { pl: "miły", en: "nice" },
  { pl: "otwarty", en: "open" },
  { pl: "optymistyczny", en: "optimistic" },
  { pl: "pesymistyczny", en: "pessimistic" },
  { pl: "otwarty, towarzyski", en: "outgoing" },
  { pl: "cierpliwy", en: "patient" },
  { pl: "niecierpliwy", en: "impatient" },
  { pl: "uprzejmy", en: "polite" },
  { pl: "cichy", en: "quiet" },
  { pl: "solidny, niezawodny/niesolidny, zawodny", en: "reliable/unreliable" },
  { pl: "odpowiedzialny", en: "responsible" },
  { pl: "niegrzeczny", en: "rude" },
  { pl: "samolubny/bezinteresowny", en: "selfish/unselfish" },
  { pl: "poważny", en: "serious" },
  { pl: "nieśmiały", en: "shy" },
  { pl: "niemądry, głupkowaty", en: "silly" },
  { pl: "towarzyski/nietowarzyski", en: "sociable/unsociable" },
  { pl: "gadatliwy, rozmowny", en: "talkative" },
  { pl: "schludny, porządny/niechlujny", en: "tidy/untidy" },
  { pl: "apodyktyczny", en: "bossy" },
  { pl: "tchórzliwy", en: "cowardly" },
  { pl: "ekscentryczny", en: "eccentric" },
  { pl: "materialistyczny", en: "materialistic" },
  { pl: "skromny", en: "modest" },
  { pl: "kapryśny", en: "moody" },
  { pl: "dziwny", en: "odd" },
  { pl: "dziwak", en: "oddball" },
  { pl: "wrażliwy", en: "sensitive" },
  { pl: "szczery", en: "sincere" },
  { pl: "życzliwy, współczujący", en: "sympathetic" },
  { pl: "dziwny", en: "weird" },
  { pl: "dziwak/dziwaczka, dziwadło", en: "weirdo" },
  { pl: "cudowne dziecko", en: "whizzkid" },
  { pl: "zamknięty w sobie", en: "withdrawn" },
  { pl: "zły, rozgniewany", en: "angry" },
  { pl: "zirytowany, rozdrażniony", en: "annoyed" },
  { pl: "być w dobrym/złym humorze", en: "be in a good/bad mood" },
  { pl: "znudzony", en: "bored" },
  { pl: "zły, rozgniewany", en: "cross" },
  { pl: "załamany, przygnębiony", en: "depressed" },
  { pl: "rozczarowany,zawiedziony", en: "disappointed" },
  { pl: "zawstydzony", en: "embarrassed" },
  { pl: "podekscytowany", en: "excited" },
  { pl: "wyczerpany, zmęczony", en: "exhausted" },
  { pl: "przerażony", en: "frightened" },
  { pl: "zdenerwowany, spięty", en: "nervous" },
  { pl: "zadowolony", en: "pleased" },
  { pl: "zrelaksowany", en: "relaxed" },
  { pl: "wystraszony", en: "scared" },
  { pl: "zszokowany", en: "shocked" },
  { pl: "zestresowany", en: "stressed" },
  { pl: "zdziwiony, zaskoczony", en: "surprised" },
  { pl: "zmęczony", en: "tired" },
  { pl: "przygnębiony, zaniepokojony", en: "upset" },
  { pl: "zmartwiony", en: "worried" },
  { pl: "zdumiony, zdziwiony", en: "amazed" },
  { pl: "zachwycony", en: "delighted" },
  { pl: "dręczące uczucie", en: "nagging feeling" },
  { pl: "przerażony", en: "petrified" },
  { pl: "zdruzgotany, wykończony", en: "shattered" },
  { pl: "oniemiały, osłupiały", en: "stunned" },
  { pl: "wycieńczony, wyczerpany", en: "worn out" },
  { pl: "uwielbiać", en: "adore" },
  { pl: "być fanem kogoś/czegoś", en: "be a fan of sb/sth" },
  { pl: "być beznadziejnym w", en: "be hopeless at" },
  { pl: "interesować się czymś", en: "be interested in sth" },
  { pl: "zajmować się czymś, interesować", en: "be into sth" },
  { pl: "interesować się, lubić coś robić", en: "be keen on sth" },
  { pl: "szaleć za kimś/czymś", en: "be mad about sb/sth" },
  { pl: "nie znosić", en: "can't stand" },
  { pl: "grać w gry/gry planszowe", en: "play games/board games" },
  { pl: "ćwiczyć", en: "work out" },
  { pl: "aborcja", en: "abortion" },
  { pl: "dobroczynność, organizacja charytatywna", en: "charity" },
  { pl: "zażywanie narkotyk", en: "drug abuse" },
  { pl: "sprawiedliwy handel", en: "fair trade" },
  { pl: "bezdomność", en: "homelessness" },
  { pl: "bezrobocie", en: "unemployment" },
  { pl: "korupcja", en: "corruption" },
  { pl: "rasizm", en: "racism" },
  { pl: "kara śmierci", en: "death penalty" },
  { pl: "eutanazja", en: "euthanasia" },
  { pl: "wolność słowa", en: "freedom of speech" },
  { pl: "hazard", en: "gambling" },
  { pl: "inżynieria genetyczna", en: "genetic engineering" },
  { pl: "prywatność", en: "privacy" },
  { pl: "krótki, krótkotrwały", en: "brief" },
  { pl: "wpaść na, natknąć się na", en: "come across" },
  { pl: "całkowity, kompletny", en: "complete" },
  { pl: "rozwinąć się w, stawać się", en: "develop into", tip: "kimś" },
  { pl: "fanatyk/fanatyczka ekologii", en: "eco-freak" },
  { pl: "fanatyk/fanatyczka ćwiczeń fizycznych", en: "fitness maniac" },
  { pl: "skupiać się na", en: "focus on" },
  { pl: "rosnąć, dorastać", en: "grow up" },
  { pl: "mieć dużo/niewiele wspólnego", en: "have a lot/little in common" },
  { pl: "osoba mająca obsesję na punkcie zdrowia", en: "health nut" },
  { pl: "ogromny", en: "huge" },
  { pl: "zidentyfikować", en: "identify" },
  { pl: "podziwiać", en: "look up to" },
  { pl: "zdać sobie sprawę", en: "realise" },
  { pl: "rozpoznać", en: "recognise" },
  { pl: "pamiętać", en: "remember" },
  { pl: "przypomnieć komuś, by coś zrobił", en: "remind someone to do something" },
  { pl: "wydawać pieniądze na", en: "spend money on" },
  { pl: "dostrzec", en: "spot" },
  { pl: "całkowite przeciwieństwo", en: "the complete opposite" },
  { pl: "typowy dla", en: "typical of" },
  { pl: "leżeć w czyjejś naturze", en: "be part of someone's nature" },
  { pl: "zaprzyjaźnić się z", en: "befriend" },
  { pl: "dziwny", en: "bizarre" },
  { pl: "nie móc uwierzyć własnym uszom", en: "can't believe your ears" },
  { pl: "częste doznanie", en: "common experience" },
  { pl: "znaleźć wspólną płaszczyznę", en: "find common ground" },
  { pl: "doskonale się bawić", en: "have the time of your life" },
  { pl: "rozpoznać, zidentyfikować", en: "place" },
  { pl: "zdobyć się na odwagę", en: "pluck up the courage", tip: "aby coś zrobić" },
  { pl: "nasuwać pytania", en: "raise questions" },
  { pl: "przeskanować, przebiec wzrokiem", en: "scan", tip: "mózg, tekst" },
  { pl: "skomplikowany, zaawansowany", en: "sophisticated" },
  { pl: "nawiązać", en: "strike up", tip: "konwersację" }
]