// Napisz poniższe słowa według wzoru: { pl: "polskie tłumaczenie", en:"angielskie słowo" }, ...
// Przykład: { pl: "blok mieszkalny", en: "block of flats"},, { pl: "budynek", en: "building" },, ...

[
  { pl: "blok mieszkalny", en: "block of flats" },
  { pl: "budynek", en: "building" },
  { pl: "dom parterowy", en: "bungalow" },
  { pl: "zamek", en: "castle" },
  { pl: "domek wiejski", en: "cottage" },
  { pl: "wolno stojący dom jednorodzinny", en: "detached house" },
  { pl: "dom rodzinny", en: "family home" },
  { pl: "dom w gospodarstwie rolnym", en: "farmhouse" },
  { pl: "mieszkanie", en: "flat" },
  { pl: "dom", en: "house" },
  { pl: "pałac, rezydencja", en: "mansion" },
  { pl: "dom spokojnej starości", en: "nursing home" },
  { pl: "bliźniak", en: "semi-detached house" },
  { pl: "kawalerka", en: "studio flat" },
  { pl: "dom szeregowy, segment", en: "terraced house" },
  { pl: "wieżowiec", en: "tower block" },
  { pl: "willa", en: "villa" },
  { pl: "domy, mieszkania w przystępnej cenie", en: "affordable housing" },
  { pl: "wszystkie wygody", en: "all mod cons" },
  { pl: "aukcja, licytacja", en: "auction" },
  { pl: "kawalerka do wynajęcia", en: "bedsit" },
  { pl: "oferta w licytacji", en: "bid" },
  { pl: "zniszczony, walący się", en: "dilapidated" },
  { pl: "osiedle mieszkaniowe", en: "housing estate" },
  { pl: "do remontu", en: "in need of renovation" },
  { pl: "przyczepa mieszkalna", en: "mobile home" },
  { pl: "mieszkanie dla emeryta", en: "retirement flat" },
  { pl: "mieszkania dla osób wymagających opieki", en: "sheltered accommodation" },
  { pl: "w budowie", en: "under construction" },
  { pl: "miasto", en: "city" },
  { pl: "dojeżdżać", en: "commute", tip: "do pracy lub do szkoły" },
  { pl: "dzielnica", en: "district" },
  { pl: "w wiejskiej okolicy", en: "in a rural area" },
  { pl: "w centrum", en: "in the centre" },
  { pl: "na wsi", en: "in the countryside" },
  { pl: "na przedmieściach", en: "in the suburbs" },
  { pl: "mieszkaniec/mieszkanka", en: "inhabitant" },
  { pl: "położony", en: "located" },
  { pl: "sąsiad/sąsiadka", en: "neighbour" },
  { pl: "sąsiedztwo, okolica", en: "neighbourhood" },
  { pl: "stare miasto", en: "Old Town" },
  { pl: "na skraju", en: "on the edge of" },
  { pl: "wychodzić na, mieć widok na", en: "overlook" },
  { pl: "transport publiczny", en: "public transport" },
  { pl: "mieszkańcy", en: "residents" },
  { pl: "widok", en: "view" },
  { pl: "wioska", en: "village" },
  { pl: "rzut kamieniem od", en: "a stone's throw from" },
  { pl: "po drugiej stronie ulicy", en: "across the road from" },
  { pl: "udogodnienia", en: "amenities" },
  { pl: "centralne położenie", en: "central location" },
  { pl: "zgiełk", en: "hustle and bustle" },
  { pl: "na głębokiej wsi", en: "in the heart of the countryside" },
  { pl: "na odludziu, w szczerym polu", en: "in the middle of nowhere" },
  { pl: "na uboczu", en: "off the beaten track" },
  { pl: "w bliskiej odległości", en: "within walking distance of", tip: "możliwej do pokonania pieszo" }
],
[
  { pl: "strych, poddasze", en: "attic" },
  { pl: "balkon", en: "balcony" },
  { pl: "piwnica", en: "basement/cellar" },
  { pl: "łazienka", en: "bathroom" },
  { pl: "sypialnia", en: "bedroom" },
  { pl: "wiata na samochód", en: "carport" },
  { pl: "sufit", en: "ceiling" },
  { pl: "komin", en: "chimney" },
  { pl: "jadalnia", en: "dining room" },
  { pl: "drzwi", en: "door" },
  { pl: "na dole, na parter", en: "downstairs" },
  { pl: "podjazd", en: "drive" },
  { pl: "ogrodzenie, płot", en: "fence" },
  { pl: "kominek", en: "fireplace" },
  { pl: "przód/tył drzwi", en: "front/back door" },
  { pl: "garaż", en: "garage" },
  { pl: "ogród", en: "garden" },
  { pl: "brama", en: "gate" },
  { pl: "parter", en: "ground floor" },
  { pl: "hol", en: "hall" },
  { pl: "żywopłot", en: "hedge" },
  { pl: "wyspa kuchenna", en: "island" },
  { pl: "kuchnia", en: "kitchen" },
  { pl: "domowa pralnia", en: "laundry room" },
  { pl: "winda", en: "lift" },
  { pl: "pokój dzienny/salon", en: "living room/lounge" },
  { pl: "strych, poddasze", en: "loft" },
  { pl: "ganek", en: "porch" },
  { pl: "dach", en: "roof" },
  { pl: "szopa", en: "shed" },
  { pl: "pokój dzienny", en: "sitting room" },
  { pl: "schody/klatka schodowa", en: "stairs/staircase" },
  { pl: "schodki", en: "steps" },
  { pl: "gabinet", en: "study" },
  { pl: "na górze, na piętrze", en: "upstairs" },
  { pl: "ściana, mur", en: "wall" },
  { pl: "alarm antywłamaniowy", en: "burglar alarm" },
  { pl: "z podwójną szybą", en: "double-glazed" },
  { pl: "przybudówka", en: "extension" },
  { pl: "staw rybny", en: "fish pond" },
  { pl: "deski podłogowe", en: "floorboards" },
  { pl: "klomb", en: "flowerbed" },
  { pl: "półpiętro", en: "landing" },
  { pl: "alarm przeciwpożarowy", en: "smoke alarm" },
  { pl: "panele słoneczne", en: "solar panels" },
  { pl: "poręcz przy schodach", en: "stair rail" },
  { pl: "pomieszczenie gospodarcze", en: "utility room" },
  { pl: "parapet okienny", en: "windowsill" },
  { pl: "przestronny", en: "airy" },
  { pl: "cegła", en: "brick" },
  { pl: "jasny", en: "bright" },
  { pl: "zagracony", en: "cluttered" },
  { pl: "wygodny", en: "comfortable" },
  { pl: "przerobić, przekształcić", en: "convert" },
  { pl: "przytulny", en: "cosy" },
  { pl: "wykończony, odnowiony", en: "decorated" },
  { pl: "przyjazny dla środowiska", en: "eco-friendly" },
  { pl: "umeblowany/nieumeblowany", en: "furnished / unfurnished" },
  { pl: "szkło, szklany", en: "glass" },
  { pl: "przytulny", en: "homely" },
  { pl: "luksusowy", en: "luxurious" },
  { pl: "utrzymywać, konserwować", en: "maintain" },
  { pl: "nowoczesny", en: "modern" },
  { pl: "błoto", en: "mud" },
  { pl: "używany, z drugiej ręki", en: "second-hand" },
  { pl: "przestronny stalowy", en: "spacious steel" },
  { pl: "kamienny", en: "stone" },
  { pl: "posprzątany/nieposprzątany", en: "tidy/ untidy" },
  { pl: "drewniany", en: "wooden" },
  { pl: "źle wykończony", en: "badly-decorated" },
  { pl: "ciasny", en: "cramped" },
  { pl: "zakurzony", en: "dusty" },
  { pl: "dębowy", en: "oak" },
  { pl: "staromodny", en: "old-fashioned" },
  { pl: "bez ścian działowych", en: "open-plan" },
  { pl: "duszny", en: "stuffy" },
  { pl: "o unikalnym wyglądzie", en: "unique-looking" },
  { pl: "dobrze utrzymany, zadbany", en: "well-maintained" },
  { pl: "meble", en: "furniture" },
  { pl: "budzik", en: "alarm clock" },
  { pl: "fotel", en: "armchair" },
  { pl: "wanna", en: "bath" },
  { pl: "łóżko", en: "bed" },
  { pl: "stolik nocny", en: "bedside table" },
  { pl: "kosz", en: "bin" },
  { pl: "koc", en: "blanket" },
  { pl: "rolety", en: "blinds" },
  { pl: "biblioteczka", en: "bookcase" },
  { pl: "półka/półki na książki", en: "bookshelf/bookshelves" },
  { pl: "dywan", en: "carpet" },
  { pl: "odtwarzacz płyt CD", en: "CD player" },
  { pl: "centralne ogrzewanie", en: "central heating" },
  { pl: "krzesło, fotel", en: "chair" },
  { pl: "komoda", en: "chest of drawers" },
  { pl: "kuchenka", en: "cooker" },
  { pl: "szafka kuchenna", en: "cupboard" },
  { pl: "zasłony/firanki", en: "curtains/net curtains" },
  { pl: "poduszka", en: "cushion", tip: "dekoracyjna" },
  { pl: "biurko", en: "desk" },
  { pl: "zmywarka", en: "dishwasher" },
  { pl: "podwójne łóżko", en: "double bed" },
  { pl: "kołdra", en: "duvet" },
  { pl: "wyposażenie, sprzęt", en: "equipment" },
  { pl: "kominek", en: "fireplace" },
  { pl: "wykładzina dywanowa", en: "fitted carpet" },
  { pl: "doniczka", en: "flowerpot" },
  { pl: "zamrażarka", en: "freezer" },
  { pl: "lodówka", en: "fridge" },
  { pl: "odkurzacz", en: "hoover" },
  { pl: "lampa", en: "lamp" },
  { pl: "światło", en: "light" },
  { pl: "oświetlenie", en: "lighting" },
  { pl: "kuchenka mikrofalowa", en: "microwave" },
  { pl: "lustro", en: "mirror" },
  { pl: "piekarnik", en: "oven" },
  { pl: "obrazek", en: "picture" },
  { pl: "poduszka", en: "pillow" },
  { pl: "plakat", en: "poster" },
  { pl: "kaloryfer", en: "radiator" },
  { pl: "dywanik", en: "rug" },
  { pl: "prześcieradło", en: "sheet" },
  { pl: "półka", en: "shelf" },
  { pl: "prysznic", en: "shower" },
  { pl: "pojedyncze łóżko", en: "single bed" },
  { pl: "zlew", en: "sink" },
  { pl: "kanapa", en: "sofa" },
  { pl: "stół", en: "table" },
  { pl: "toster", en: "toaster" },
  { pl: "toaleta, sedes", en: "toilet" },
  { pl: "telewizor", en: "TV set" },
  { pl: "tapeta", en: "wallpaper" },
  { pl: "szafa", en: "wardrobe" },
  { pl: "umywalka", en: "washbasin" },
  { pl: "pralka", en: "washing machine" },
  { pl: "zabytkowy, staroświecki", en: "antique" },
  { pl: "miska na owoce", en: "fruit bowl" },
  { pl: "wskazówka", en: "hand", tip: "zegara" },
  { pl: "czajnik", en: "kettle" },
  { pl: "sprzęt kuchenny", en: "kitchen appliances" },
  { pl: "przybory kuchenne", en: "kitchen utensils" },
  { pl: "półka nad kominkiem", en: "mantelpiece" },
  { pl: "ozdoba", en: "ornament" },
  { pl: "roślina doniczkowa", en: "potted plant" },
  { pl: "okiennice", en: "shutters" },
  { pl: "srebrna ramka", en: "silver frame" },
  { pl: "półka, stojak", en: "rack" }
],
[
  { pl: "gospodarstwo domowe", en: "household" },
  { pl: "zmienić pościel", en: "change the sheets" },
  { pl: "pracować w ogrodzie", en: "do the gardening" },
  { pl: "zajmować się domem", en: "do the housework" },
  { pl: "opróżniać zmywarkę", en: "empty the dishwasher" },
  { pl: "mieć dobrą rękę do roślin", en: "have green fingers" },
  { pl: "odkurzać dywan", en: "hoover the carpet" },
  { pl: "prasować ubrania", en: "iron the clothes" },
  { pl: "ścielić łóżko", en: "make the bed" },
  { pl: "kosić trawnik", en: "mow the lawn" },
  { pl: "zamiatać podłogę", en: "sweep the floor" },
  { pl: "porządkować biurko", en: "tidy the desk" },
  { pl: "miotła", en: "broom" },
  { pl: "szczotka", en: "brush" },
  { pl: "ściereczka do kurzu", en: "duster" },
  { pl: "kosiarka", en: "lawnmower" },
  { pl: "grabie", en: "rake" },
  { pl: "gumowe rękawiczki", en: "rubber gloves" },
  { pl: "szpadel", en: "spade" },
  { pl: "rydel", en: "trowel" }
],
[
  { pl: "zakwaterowanie", en: "accommodation" },
  { pl: "ogłoszenie, reklama", en: "ad/advert" },
  { pl: "współlokator/współlokatorka", en: "flatmate/housemate/roommate" },
  { pl: "na sprzedaż", en: "for sale" },
  { pl: "właściciel/właścicielka (mieszkania lub domu)", en: "landlord/landlady" },
  { pl: "mieszkać samemu", en: "live on one's own" },
  { pl: "wprowadzić się/wyprowadzić się", en: "move in/move out" },
  { pl: "zapłacić z góry", en: "pay in advance" },
  { pl: "wynająć; czynsz", en: "rent" },
  { pl: "dzielić z kimś pokój/mieszkanie/dom", en: "share a room/flat/house" },
  { pl: "do wynajęcia", en: "to let" },
  { pl: "rachunek", en: "bill" },
  { pl: "budżet", en: "budget" },
  { pl: "liczyć, pobierać opłatę", en: "charge" },
  { pl: "kaucja, zaliczka", en: "deposit" },
  { pl: "agent/agentka nieruchomości", en: "estate agent" },
  { pl: "parapetówka", en: "housewarming" },
  { pl: "raty", en: "installments" },
  { pl: "wypowiedzenie", en: "notice" },
  { pl: "płatność", en: "payment" },
  { pl: "tygodniowo/miesięcznie", en: "per week/per month" },
  { pl: "wziąć kredyt hipoteczny", en: "take out a mortgage" },
  { pl: "najemca, lokator", en: "tenant" }
],
[
  { pl: "w przystępnej cenie", en: "affordable" },
  { pl: "poza", en: "beyond" },
  { pl: "skarżyć się, narzekać", en: "complain" },
  { pl: "upiększyć, podkolorować", en: "embellish" },
  { pl: "w pełni umeblowany", en: "fully furnished" },
  { pl: "nie spuszczać (kogoś/czegoś) z oczu", en: "keep your eyes on" },
  { pl: "tęsknić za", en: "miss" },
  { pl: "w pobliżu, pobliski", en: "nearby" },
  { pl: "niebezpieczny", en: "rough" },
  { pl: "ostry", en: "sharp" },
  { pl: "wzdychać; westchnienie", en: "sigh" },
  { pl: "wpatrywać się w", en: "stare at" },
  { pl: "dąsać się", en: "sulk" },
  { pl: "maleńki, niewielki", en: "tiny" },
  { pl: "być szalonym", en: "be off your head" },
  { pl: "nieostry, zamazany", en: "blurry" },
  { pl: "wpaść na kogoś, spotkać kogoś przypadkiem", en: "bump into" },
  { pl: "wsiąść", en: "get into" },
  { pl: "zrobić awanturę", en: "kick up a fuss" },
  { pl: "pełen zakamarków", en: "rambling" },
  { pl: "zniszczony, podupadły", en: "run-down" },
  { pl: "przytulny, zaciszny", en: "snug" },
  { pl: "samotność", en: "solitude" },
  { pl: "wciśnięty", en: "squashed" },
  { pl: "plama", en: "stain" },
  { pl: "wlewać się", en: "stream in" },
  { pl: "natknąć się na", en: "stumble upon" },
  { pl: "zmienić się w, przeobrazić się w", en: "turn into" },
  { pl: "pojawić się na", en: "turn up for" },
  { pl: "pochłonięty czymś", en: "wrapped up in" }
]