const questions = {
  c1s1: [
    { pl: "dane osobowe", en: "personal data" },
    { pl: "adres", en: "address" },
    { pl: "wiek", en: "age" },
    { pl: "data urodzenia", en: "date of birth" },
    { pl: "rozwiedziony", en: "divorced" },
    { pl: "kobieta", en: "female" },
    { pl: "imię", en: "first name" },
    { pl: "płeć", en: "gender" },
    { pl: "mężczyzna", en: "male" },
    { pl: "stan cywilny", en: "marital status" },
    { pl: "żonaty/zamężna", en: "married" },
    { pl: "narodowość", en: "nationality" },
    { pl: "zawód", en: "occupation" },
    { pl: "stanu wolnego", en: "single" },
    { pl: "nazwisko", en: "surname" },
    { pl: "owdowiały", en: "widowed" },
    { pl: "kraj zamieszkania", en: "country of residence" },
    { pl: "znaki szczególne", en: "distinguishing features" },
    { pl: "pochodzenie etniczne", en: "ethnic origin" },
    { pl: "najbliższy krewny", en: "next of kin" }
  ],
  c1s2: [
    { pl: "wygląd zewętrzny", en: "appearance" },
    { pl: "atrakcyjny/nieatrakcyjny", en: "attractive/unattractive" },
    { pl: "piękny", en: "beautiful" },
    { pl: "sprawny", en: "fit" },
    { pl: "przystojny, ładny", en: "good-looking" },
    { pl: "przystojny", en: "handsome" },
    { pl: "pospolity, nieatrakcyjny", en: "plain" },
    { pl: "ładny", en: "pretty" },
    { pl: "brzydki", en: "ugly" },
    { pl: "ograniczać", en: "cut down on", tip: "ilość czegoś" },
    { pl: "wybierać, sięgać po", en: "go for", tip: "ciemniejsze kolory" },
    { pl: "malować paznokcie", en: "paint nails" },
    { pl: "przybierać/tracić", en: "put on/lose", tip: "na wadze" },
    { pl: "prostować", en: "straighten", tip: "włosy" },
    { pl: "zacząć", en: "take up", tip: "hobby, sport" },
    { pl: "gruby", en: "fat" },
    { pl: "umięśniony", en: "muscular" },
    { pl: "otyły", en: "obese" },
    { pl: "z nadwagą/z niedowagą", en: "overweight/underweight" },
    { pl: "puszysty/pulchny", en: "plump" },
    { pl: "chudy", en: "skinny" },
    { pl: "szczupły", en: "slim" },
    { pl: "dobrze zbudowany", en: "well-built" },
    { pl: "tyczkowaty, wysoki i chudy", en: "lanky" },
    { pl: "krępy", en: "stocky" },
    { pl: "łysy", en: "bald" },
    { pl: "blond", en: "blond" },
    { pl: "kręcone", en: "curly" },
    { pl: "ciemne", en: "dark" },
    { pl: "farbowane", en: "dyed" },
    { pl: "rude", en: "red" },
    { pl: "do ramion", en: "shoulder-length" },
    { pl: "proste", en: "straight" },
    { pl: "falujące", en: "wavy" },
    { pl: "kasztanowe", en: "auburn" },
    { pl: "cienkie, rzadkie/gęste", en: "fine/thick" },
    { pl: "grzywka", en: "fringe" },
    { pl: "mieć przedziałek na środku/z boku", en: "have a center/side parting" },
    { pl: "kita, koński, ogon", en: "ponytail" },
    { pl: "włosy rzednące na skroniach", en: "receding hairline" },
    { pl: "nosić włosy rozpuszczone/spięte", en: "wear your hair loose/up" },
    { pl: "broda", en: "beard" },
    { pl: "piegi", en: "freckles" },
    { pl: "wąsy", en: "moustache" },
    { pl: "blada/opalona/ciemna cera", en: "pale/tanned/dark complexion" },
    { pl: "przekłute uszy", en: "pierced ears" },
    { pl: "blizna", en: "scar" },
    { pl: "pryszczaty", en: "spotty" },
    { pl: "tatuaż", en: "tattoo" },
    { pl: "zmarszczki", en: "wrinkles" },
    { pl: "znamię", en: "birthmark" },
    { pl: "gładko ogolony", en: "clean-shaven" },
    { pl: "gładka skóra", en: "clear-skin" },
    { pl: "podwójny podbródek", en: "double chin" },
    { pl: "wystające kości policzkowe", en: "high cheekbones" },
    { pl: "wysokie czoło", en: "high forehead" },
    { pl: "przenikliwe niebieskie oczy", en: "piercing blue eyes" }
  ],
  c1s3: [
    { pl: "bluzka", en: "blouse" },
    { pl: "wysokie buty, kozaki", en: "boots" },
    { pl: "biustonosz", en: "bra" },
    { pl: "codzienny, swobodny", en: "casual" },
    { pl: "płaszcz", en: "coat" },
    { pl: "sukienka", en: "dress" },
    { pl: "modny", en: "fashionable/trendy" },
    { pl: "bluza polarowa", en: "fleece" },
    { pl: "rękawiczki", en: "gloves" },
    { pl: "kapelusz, czapka", en: "hat" },
    { pl: "kurtka, marynarka, żakiet", en: "jacket" },
    { pl: "dżinsy", en: "jeans" },
    { pl: "sweter", en: "jumper" },
    { pl: "staromodny, staroświecki", en: "old-fashioned" },
    { pl: "piżama", en: "pyjamas" },
    { pl: "sandały", en: "sandals" },
    { pl: "koszula", en: "shirt" },
    { pl: "buty", en: "shoes" },
    { pl: "szorty", en: "shorts" },
    { pl: "spódnica", en: "skirt" },
    { pl: "elegancki", en: "smart" },
    { pl: "skarpety", en: "socks" },
    { pl: "garnitur", en: "suit" },
    { pl: "bluza sportowa", en: "sweatshirt" },
    { pl: "krawat", en: "tie" },
    { pl: "dres", en: "tracksuit" },
    { pl: "obuwie sportowe", en: "trainers" },
    { pl: "spodnie", en: "trousers" },
    { pl: "bielizna", en: "underwear" },
    { pl: "kamizelka", en: "waistcoat" },
    { pl: "nosić, mieć na sobie", en: "wear" },
    { pl: "suknia balowa, strój balowy", en: "ballgown" },
    { pl: "z szerokim dekoltem", en: "boat-necked" },
    { pl: "rozpinany sweter", en: "cardigan" },
    { pl: "kołnierzyk", en: "collar" },
    { pl: "mankiety", en: "cuffs" },
    { pl: "szlafrok", en: "dressing gown" },
    { pl: "wysokie obcasy", en: "high heels" },
    { pl: "bluza z kapturem", en: "hoodie" },
    { pl: "z długim rękawem/z krótkim rękawem", en: "long-sleeved/short-sleeved" },
    { pl: "bluzka bez ramiączek", en: "strapless top" },
    { pl: "dekolt w szpic", en: "V-neck" },
    { pl: "dodatki", en: "accessories" },
    { pl: "pasek", en: "belt" },
    { pl: "guzik", en: "button" },
    { pl: "czapka z daszkiem", en: "cap" },
    { pl: "kolczyki", en: "earrings" },
    { pl: "okulary", en: "glasses" },
    { pl: "torebka", en: "handbag/bag" },
    { pl: "biżuteria", en: "jewellery" },
    { pl: "naszyjnik", en: "necklace" },
    { pl: "pierścionek", en: "ring" },
    { pl: "szalik", en: "scarf" },
    { pl: "krawat", en: "tie" },
    { pl: "bransoletka", en: "bracelet" },
    { pl: "broszka", en: "brooch" },
    { pl: "sznurówki", en: "shoe laces" },
    { pl: "kapcie", en: "slippers" },
    { pl: "na zamek", en: "zip-up" },
    { pl: "w kratę", en: "checked" },
    { pl: "bawełna", en: "cotton" },
    { pl: "złoto", en: "gold" },
    { pl: "skóra, skórzany", en: "leather" },
    { pl: "gładki", en: "plain" },
    { pl: "jedwab", en: "silk" },
    { pl: "srebro, srebrny", en: "silver" },
    { pl: "w kropki", en: "spotted" },
    { pl: "w paski", en: "stripped" },
    { pl: "w szkocką kratę", en: "tartan" },
    { pl: "wełna", en: "wool" },
    { pl: "elastyczny", en: "elastic" },
    { pl: "futro, futrzany", en: "fur" },
    { pl: "koronkowy", en: "lacy" },
    { pl: "na doszewce, ocieplany", en: "lined" }
  ],
  c1s4: [
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" },
    // { pl: "sprawny", en: "fit" }
  ],
  c1s5: [
    { pl: "suka", en: "bitch" },
  ],
  c1s6: [
    { pl: "kobieta", en: "woman" },
  ]
  // Add more questions as needed
};